### ISSUE TITLE
Sorting is broken on tree grids (ag-grid bug)

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#1024]
Sorting no longer works on tree grids, easily repro-able in toolbox. 

This appears to be a bug in the latest version of ag-grid. It is easily repro-able in their [File Explorer tree grid demo](https://www.ag-grid.com/javascript-grid-tree-data/#example-file-browser) by clicking the Add New Group button. After adding the new group, sorting no longer works.

Turning off `deltaRowDataMode` in the ag-grid grid options appears to fix the issue. Also calling `gridApi.refreshClientSideRowModel()` after updating the row data fixes the issue. This appears to be an issue with tree data whenever you do a delta update to the row data, either via `updateRowData` or `setRowData` with `deltaRowDataMode` on.

I don't think there is any action needed to be taken in hoist for this, unless we want to roll back the ag-grid upgrade, but adding this here for our own tracking/information.

**Comment by lbwexler** [comment]
John -- need to continue tracking this.  Will also relate to general grid discussions around deltaRowDataMode that we should have this week....

**Comment by amcclain** [comment]
Reported by ag-grid as fixed by update in #1039.
