### ISSUE TITLE
Primary HoistInput CSS class should live on outermost rendered element

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1027]
Looking at a textInput() usage at the moment, and noticed that we are wrapping the input in an outer div to set sizing, etc. but that the `.xh-text-input` class is still applied to the inner div, so this outer wrapper with the fixed size on the element ends up being somewhat mysterious / not clearly part of the overall textInput control.

I think we should move the primary className to the outer wrapper - any reason not to do so? 

Assume this likely applies to other inputs - filing here quickly so as not to forget.

**Comment by TomTirapani** [comment]
Look at this - agreed, there doesn't seem to be any need for this anomaly, nor any problem in fixing it. Fixed in https://github.com/exhi/hoist-react/commit/41c4455ee1acf6fee145144c306620f22fcb1f49. Desktop `TextInput` was the only input that needed this change.

**Comment by amcclain** [comment]
Great - thanks, and nice that it was just that one component!
