### ISSUE TITLE
Form Context: Dynamic children crash app

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#1031]
Dynamically adding children to a Form context, even simple layout elements, will crash the app.

Encountered this tricky bug in a client app. For context, I had something like the following:

```
form(
	formField(),
	formField(),
	div({omit: !model.showErrorMsg, item: 'Error message...'}),
	formField(),
	formField(),
	formField(),
	formField()
)
```

When `model.showErrorMsg: true` and the div is no longer omitted, the subsequent FormField had their FieldModels shifted. This caused Model Change Exceptions, which brought the app down. My current theory is that the 'new' div has been given a FieldModel.

I understand that we support SubForms for dynamically adding FormFIelds, but I would expect other components to be dynamic in a Form context without issue.

My workaround for now is to set `style: {display: none}` rather than `omit: true`.

**Comment by TomTirapani** [comment]
I tried to replicate this in Toolbox, but couldn't... then tried to replicate in the client app where I original saw it reliably, and also couldn't!

So not entirely sure what happened there, but think we can ignore this for now and keep it in mind if it appears again...

**Comment by amcclain** [comment]
You bet - agree then let's close it for now.  I will keep an eye out, and still glad you posted.  Something like this usually comes back around eventually, or points at some other issue we will see again.

**Comment by TomTirapani** [comment]
This has resurfaced in the process of upgrading a client-app to latest hoist-react. Will take another look.

**Comment by TomTirapani** [comment]
Managed to reproduce in Toolbox.

Error occurs when re-rendering changes the order of sibling FormFields. React doesn't have a way to determine that the newly added FormField isn't one that was there before, and so tries to repurpose it with a different FieldModel, causing the error. The solution is to use `key` to identify each FormField, allowing React to better identify what should change on re-render.

Fixed here: https://github.com/exhi/hoist-react/pull/1063
