### ISSUE TITLE
Hoist Admins should always see the footer/version bar

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1034]
We don't show our standard footer with version info in production by default - the logic being that standard business users don't need this technical info taking up space in the layout.

However we do support a pref to force the version bar to be shown, and I've been in the habit of setting this for myself for various prod app instances.  Thinking it would be beneficial to have it always shown for Hoist Admins so I and other devs (who typically have admin access) don't need to fiddle with preferences.  For us it's pretty important to have that version and visual cue to the current environment always present.

**Comment by lbwexler** [comment]
Let's remove (deprecate) the existing preference here

**Comment by lbwexler** [comment]
👍 Good way to know if you are a Hoist Admin too!
