### ISSUE TITLE
HoistInput: Use onKeyDown rather than onKeyPress

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#1040]
Should we consider replacing the numerous uses of `onKeyPress` in HoistInputs with `onKeyDown`? There are two motivating factors:

1) The `keypress` event is deprecated: https://developer.mozilla.org/en-US/docs/Web/Events/keypress. The recommendation is to replace with `keydown`. Not expecting browser support to disappear anytime soon, but I think would be better to be up to date.

2) The `keypress` event only fires for certain keys - specifically, keys that "produce a character value (alphabetic, numeric, and punctuation keys)". We recently wanted to use it to listen to arrow keys - it did not fire for these keys, yet `keydown` would have.

**Comment by amcclain** [comment]
Sounds like a pretty clear move to me - could there be any downside / usages we can anticipate breaking?  I say let's go ahead.

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/1043

**Comment by amcclain** [comment]
Great thanks - will review and test it out soon.  These inputs are tricky enough that I do want to ensure we test thoroughly, but change looks good and I am sure we will take it shortly.
