### ISSUE TITLE
FileChooser.enableMulti prop is misleading / not what we want

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1069]
Believe I misunderstood what the `multiple` prop on react-dropzone does, and so our doc / expectation on the Hoist component's `enableMulti` is confusing. 

https://github.com/exhi/hoist-react/blob/744ff7f51d1b873ba93748218bd8f8c37f6fe2be/desktop/cmp/filechooser/FileChooser.js#L44

It implies that if true the component will only deal with one file overall - i.e. preventing further clicks or drags if there's a file selected and requiring the user to remove that file before choosing another.  But instead it is [this input attr](https://html.spec.whatwg.org/multipage/input.html#attr-input-multiple) which is not the same thing. This appears to only limit how many files the user can choose at once within the OS file picker pop-up shown by the browser.

There could be a valid use-case for only allowing the user to tee up one file at a time into our chooser, so we should look to keep the prop but make it work how we would expect.

We might also wish to expose a `singleFile` observable, equiv to `StoreSelectionModel.singleRecord` that is populated iff there is a single file in the list.

**Comment by lbwexler** [comment]
Let's either fix this (if can be done relatively easily), or remove it for now.  No need to leave broken features in the API that aren't currently in use!

Definitley don't want to make a big project of it

**Comment by lbwexler** [comment]
Fixed!  Yana making a toolbox example now.
