### ISSUE TITLE
'X' close button on modal dialog is off center

### ISSUE THREAD

**Issue by YanaNirvana** [exhi/hoist-react#1078]
'X' (close) button outline is off center when hovering over it

<img width="695" alt="Screen Shot 2019-04-17 at 2 39 31 PM" src="https://user-images.githubusercontent.com/30638175/56312672-b1b73d80-611e-11e9-9785-60b701d3ace0.png">

**Comment by amcclain** [comment]
Thanks for filing!  Drives me crazy.
