### ISSUE TITLE
StoreFilterField loses state on unmount

### ISSUE THREAD

**Issue by shravnk** [exhi/hoist-react#1086]
Specifically referring to the `value` observable which populates the component's TextInput. `value` is reset on unmount because it's defined on the StoreFilterField component itself. @lbwexler and I discussed:

1. Binding to a `LocalStore` property
2. Requiring the value to be manually defined (e.g. on the enclosing `Panel`'s model)

**Comment by lbwexler** [comment]
(comment from initial PR, which placed the state for the comment on the Store itself:)

Cool idea, but would like to really keep Store unaware of Store filter-field's state. Its an inversion of the layers, and not worth it to fix this bug.

If we really want to associate the filter state with that store in a stateful way, and we don't want to build a dedicated model in store filter field, or have it use its parent to hold the state, we could consider a static map in store filter field, of store.xhId to filter text.
