### ISSUE TITLE
DockContainer view z-index vs. mask

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1103]
If a component is shown in a DockContainer and another component _underneath_ the view is masked, that other component's mask will cover the docked view.

(Again for clarity, the component showing the mask is not within the DockContainer - it's in the primary layout along the bottom edge of the app.)

We want DockContainer views to act like dialogs, in that their overall z-index is higher than non-floating app components.

(I can show a real-world example in a client app if helpful.)

**Comment by TomTirapani** [comment]
Fixed here - should be quick merge: https://github.com/exhi/hoist-react/pull/1105

**Comment by amcclain** [comment]
Thanks for jumping on this - appreciate it.
