### ISSUE TITLE
ButtonGroupInput should allow buttons to be unselected (aka inactive)

### ISSUE THREAD

**Issue by YanaNirvana** [exhi/hoist-react#1110]
Currently, once a button in a ButtonGroupInput it selected, it cannot be unselected.

It might be nice for ButtonGroupInput to take in an optional `enableClear` that allows a button to be unselected.

**Comment by lbwexler** [comment]
We went ahead and did this.  Think its very elegant, clean, and also not enabled by default (for consistency with the other inputs).
