### ISSUE TITLE
Minor PanelModel config / splitter issues

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1119]
* We should show a splitter on a Panel with a model configured as `resizable: true` and `collapsible: false`.  Currently we draw it without the splitter but you can weirdly grab an invisible border to resize.
* We should not create a header for that same resizable: true / collapsible: false Panel if it does not have a title, icon, or headerItems of its own.  Currently we do, and you weirdly need to set `showHeaderCollapseButton: false` to suppress.

**Comment by YanaNirvana** [comment]
Merged.  See #1135
