### ISSUE TITLE
413 Request Entity Too Large Error on grid export

### ISSUE THREAD

**Issue by nadkarniarjun** [exhi/hoist-react#1134]
Export through Hoist resulted in 413 Entity Too Large error. 

We attempted to change two parameters, but neither worked. 

**In docker/nginx/app.conf**:
`<server>
...
    client_max_body_size 0;
</server>
`
and
**application.groovy**:
`        controllers {
            upload {
                maxFileSize = 20971520
                maxRequestSize = 20971520
            }
        }
`
The application is deployed and managed through Kubernetes

**Comment by nadkarniarjun** [comment]
@amcclain When you get a chance, I'd like to look through this one with you, please.

**Comment by amcclain** [comment]
Hi Arjun - apologies I was out of the office for a few days.  I assume this is still an issue?

How large is the attempted POST? Note that the xh-nginx base image [sets a limit of 20MB](https://github.com/exhi/xh-nginx/blob/42f4149a7c53ca697adda32725acb76973df06b1/xh.conf#L20). Given this, we shouldn't need to customize the app's dockerfile unless we need to go larger - especially as I believe that Grails-side value remains at 20MB (`20971520/1024/1024`).

I am not sure, but it's also possible that this error is coming from the k8s ingress.  Did you see an nginx error page returned? If so, did the version reported match the version of nginx we're packaging? Our dockerfile [specifies nginx:latest](https://github.com/exhi/xh-nginx/blob/42f4149a7c53ca697adda32725acb76973df06b1/Dockerfile#L1) which [should be 1.15.12](https://hub.docker.com/_/nginx/).

**Comment by nadkarniarjun** [comment]
Hi Anselm. Yes, this is still an issue. 

Here are some more details:
1. It first failed on a POST that was a little under 5MB in size, so we added in `client_max_body_size 5M;` in the `app.conf` file. Once we did that, and deployed to UAT, that original export worked. 
2. Upon further testing, however, the user found another export that failed with a POST content size of 6791091 (~6.5MB). Further increases in `client_max_body_size` did not fix this use case. We even tried an unlimited size of `client_max_body_size 0;` with no luck. 

P.S. Neither the user nor I were able to recreate this on our local environments. All exports worked fine locally. This was only an issue in the UAT / Prod environments.

**Comment by amcclain** [comment]
This was a limit imposed by the client's Rancher deployment, which had a default (low) limit in place for its nginx-based ingress.

A crucial hint that this was not our nginx came from the fact that the error message in the 413 response included a different nginx version number than e.g. a 404.  Looking at the nginx logs within the Rancher cluster also did not show any sign of the error, indicating it was being intercepted before it reached our stack.

Resolved by adding the `nginx.ingress.kubernetes.io/proxy-body-size` annotation with a larger `20m` value.  Client infrastructure team contacted and asked if they can make this a default.
