### ISSUE TITLE
Add XH.prompt()

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#1139]
Just an idea, filing here so I don't forget...

Add an XH.prompt() method, that shows a configurable Message that contains a TextInput. On clicking confirm, the promise resolves with the typed in value.

Motivation here is that:
- Often you don't want to go to whole trouble of setting up a dialog / form to collect some information during a user action.
- window.prompt() is the only native dialog method that doesn't have an XH analogue.
- We had something similar in the Sencha toolkit.

**Comment by TomTirapani** [comment]
See PRS:
https://github.com/exhi/hoist-react/pull/1170
https://github.com/exhi/toolbox/pull/203

**Comment by lbwexler** [comment]
👍
