### ISSUE TITLE
Support Ctrl-A select all rows in grid

### ISSUE THREAD

**Issue by pauldelano** [exhi/hoist-react#1149]
ag-Grid supports keyboard shortcuts like Ctrl-C Copy but not Ctrl-A Select-all.

It can be implemented in an application by adding a grid keyDown event handler:
```
keyDown(evt) {
  if (evt.ctrlKey && evt.key == 'a') {
    gridModel.agAPi.selectAllFiltered();
  }
}
```
See related selModel issue #1150.

**Comment by lbwexler** [comment]
I took this and implemented it here, but am finding that our selModel's attempt to do selectAll() is still unbelievably slow.  I thought we fixed this?
