### ISSUE TITLE
Improve performance of programmatic grid select

### ISSUE THREAD

**Issue by pauldelano** [exhi/hoist-react#1150]
When a grid selModel has many rows selected, it gets quite slow. It can take tens of seconds for a thousand rows.

For example, to select all rows:
* This is slow: gridModel.selModel.select(gridModel.store.records, true);
* The native ag-Grid select all is fast: gridModel.agApi.selectAllFiltered();

**Comment by amcclain** [comment]
Thanks for filing this - we always want to be super-aware of cases where the Hoist approach is meaningfully slower than direct access to component APIs!

I see we are setting them one-by-one in the AgGridModel - this must be what is so slow:

https://github.com/exhi/hoist-react/blob/27e0ce3fa2e5770382c1a9fc7f3c6a18d4fa6ef1/cmp/ag-grid/AgGridModel.js#L333

Would want to know if there's a better AG API to call to set a batch of records as selected in general - if not, or if not helpful, providing some dedicated API methods to select all would make sense.
