### ISSUE TITLE
Improve column selection options in GridExportService

### ISSUE THREAD

**Issue by pauldelano** [exhi/hoist-react#1155]
The GridExportService has an option includeHiddenCols. However, it can be helpful to include the id or other fields on export.

Add one and or the other of these options:
1. cols - A list of columns to export
2. requiredCols - A list of columns that are added to visible columns if they are hidden.

**Comment by amcclain** [comment]
Would it be too weird to support a single `columns` option that could take:
• Special string `ALL` to export all cols
• Special string `VISIBLE` to export all visible cols
• List of colIds to specify cols.  List can also itself contain special token `VISIBLE` to include specified ids + all visible columns.

I acknowledge it's a bit fiddly to have the config support multiple input types (string or array) with these special tokens, but I think it might still be preferable to splitting the setting across multiple configs where you need to work out how they interact, or could specify silly combinations.

As discussed out-of-band, we could leave guarantees about ordering for another iteration.

@lbwexler thoughts on the API here whenever you have a chance?

**Comment by lbwexler** [comment]
I like your suggestion, anselm.  Don't think it's too fiddly.

-Lee
