### ISSUE TITLE
Turning off tail mode in Admin log viewer reverses order of all lines

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1166]
Tail mode (default) is intended to load the most recent n lines of the log file and auto-refresh to keep updating and tracking the latest changes to the log file.

Turning off tail mode should load the log starting on the startLine and loading maxLines worth of the log file.  The first line should still be at the top - not sure why it's now flipped around but I don't think it's usable or intentional...

**Comment by lbwexler** [comment]
👍
