### ISSUE TITLE
Improve Handling when Grails backend unavailable

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#1187]
We have two issues here --

1) Our error message is still too wonky ("EnvironmentService blah, blah..") We need to get right to the point about the "UI Server is Unavailable".

2) If you go ahead and try to submit the error, that just fails and annoyingly does nothing, and does not close the dialog.

I think 2 is probably something we can handle with better exception handling generally on that button action.... should never just fail silently like that!  Its just heaping more pain on an already suffering user....

**Comment by lbwexler** [comment]
Yana -- are you working on this yet?  if not, would like to give it to Don

**Comment by YanaNirvana** [comment]
not yet, it's all Don's!
