### ISSUE TITLE
Grid export - scale mismatch when exporting percent values

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1192]
Configure a grid column showing a percent value with `renderer: percentRenderer()` and `exportFormat: ExportFormats.PCT` - the exported value will display 100x the rendered value.

Not sure if this is possible to workaround - the Excel format makes it clear (within the Excel "format cells" UI) that it will display the value x100 with a percent sign.  Can workaround by providing `exportValue: v => v/100` - but should our percentRenderer match Excel's behavior and also x100 for display?  Would that be more natural in general?  (If so we can close this ticket or modify to make it about the renderer itself.)

**Comment by lbwexler** [comment]
Don had some cycles, and is the original expert on formatting
