### ISSUE TITLE
Remove "are you sure" prompts on config/pref edits

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1204]
These start to get very annoying when you are looking to update  a number of configs.

**Comment by lbwexler** [comment]
Don said he had a few cycles....

**Comment by febbraiod** [comment]
Those cycles got eaten up really quickly last week.

Finally got to look at this one. I don't see a warning for editing configs, but do see one for prefs. Removed for prefs, but wondering if the intention was to remove warning for deleting as well (I wouldn't think so).

**Comment by amcclain** [comment]
Thank you for checking.  I think it must have been the pref editing prompt that caused me to put this ticket in.  I was looking to sync up prefs across two environments for a release (after getting the configs all in place first) and the prompts (with their exclamation points at the end) were starting to wear thin.

But looking at it now, I agree we really need a prompt for deletes - it's too dangerous to have a single click on the button zap a config. (Supporting multi-select and deletes would also help minimize clicking, but that's another ticket.)

**Comment by amcclain** [comment]
Fixed in 7b7a12d9c4b274549371834c60fa393a728bfe68
