### ISSUE TITLE
Move mobile app menu to right

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1207]
To the right of the default refresh button - far right of appBar  

Most importantly to me this is consistent with the desktop which I think makes sense for this particular built in component.

But it would also allow an app logo glyph to appear first which I like and - when the back nav button is active - lets that button come and go without moving the anchor position for the main menu  

Happy to be convinced otherwise of course. 

Could also be an app bar prop like appMenuPosition that could take "none" to suppress I'd we really needed - but I would prefer it be consistent

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/1217
https://github.com/exhi/toolbox/pull/216
