### ISSUE TITLE
Support custom Column sort comparators

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#1216]
The only way to achieve this currently is to use `agOptions` to specify a comparator, but it would be nice if we supported `comparator` as a first-level property on our Column config and it was passed Hoist data structures (records, column, store, gridModel, etc.) instead of having to use the ag-Grid RowNode objects if you need to inspect anything other than the value.

Would also want to make sure we pass the `absSort` flag to the comparator.

**Comment by haynesjm42** [comment]
Specific use-case from client here is to have root-level tree rows use a static sorting, while sorting their children alphabetically.

**Comment by haynesjm42** [comment]
So on further investigation with @YanaNirvana we realized that a per-column sort comparator would not be ideal to solve this issue, as a comparator would need to be added for each column.

ag-Grid does provide a `postSort` callback which we can implement to force certain rows to static positions after other sorting has been applied. Unfortunately ag-Grid's api for this requires mutating an array of RowNodes, so the implementation might get a bit messy if we want to add a layer on top of this in our framework. @lbwexler would like to get your thoughts on whether we should add our own `postSort` callback to GridModel. I do think the original request in this ticket is valid and something we should still do though.

**Comment by YanaNirvana** [comment]
Just to collect things together in the same space:

https://www.ag-grid.com/javascript-grid-sorting/#post-sort

(John's keen eye spotted that in their example, they don't return anything-- they mutate in place using `splice`)

**Comment by lbwexler** [comment]
Hi -- This is fine for Hoist 25, which we will look to go out this week.  I discussed with client that is waiting for it.
