### ISSUE TITLE
JsonInput option for a maximized or "pop-out" view

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#1228]
Perhaps a modal popup of some sort? Or a grow affordance? 

Would be nice to have the control handle it, so the form containing the control does not need to add special handling to get a usable editor.

I am about ready to poke my eyes out editing these configs in the little window config viewer is giving me....

**Comment by lbwexler** [comment]
its all yours panda

**Comment by amcclain** [comment]
Thanks for filing this - has been on my mental list for some time.  

Agree that ideally this would be a feature nicely encapsulated / managed by the JsonInput itself.  I think a modal pop-out would be most useful with some kind of little way to launch.  

I don't know if it can support some kind of baby toolbar inside of the editor.  If so, I can imagine that hosting a button to pop-out as well as a button to pretty-print (currently supported via a very obscure keyboard shortcut).  I think we would want a prop to suppress this toolbar if not wanted, but could default to on.  I am thinking of something as minimal and unobtrusive as possible, while still being obvious enough that users will find and make use of it.

**Comment by lbwexler** [comment]
This has become a high priority.  We have very lunch json configs to edit in some client apps, and only 5 visible lines to do it in our config editor.

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/1267
