### ISSUE TITLE
loadAsync method in loadSupport will not always default the loadSpec as desired

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#1237]
This was discovered while working on:

https://github.com/exhi/toolbox/issues/217

Arguably, toolbox is not using loadSupport correctly, but I think there is a safe change to be made in HR that will avoid this issue.

**Comment by lbwexler** [comment]
I think you are right Don,  toolbox not using loadSupport correctly.  

Handling the null case seems like just one very small fix for a particular case.  It's really critical that we avoid the misuse....
