### ISSUE TITLE
Default GridModel.enableExport to true

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1259]
Currently defaults to false, so we're adding the config line to enable in what I bet are a large majority of application grids.

Seems like defaulting to true is pretty safe - worst thing that could happen is a user could discover the context menu and trigger an export.  For small utility grids or other cases where we don't want that, easy to disable.  Everywhere else, save a line of config code.

I don't _think_ we need to consider this a breaking change if we note it in the CHANGELOG (if we were going the other way, yes, but here the stakes seem pretty low and apps will still work just fine).

**Comment by TomTirapani** [comment]
The original intention behind making export 'opt-in' was to remind devs that enabling export requires more thought than just setting enableExport - they also have to ensure the columns in their grid have the correct exportFormat / exportValue. Most grids are not ready for export by default.

Not saying we shouldn't make this change - just thought I should highlight that concern. I suppose its not a big deal if they don't configure the columns properly, but we'll just have to make sure any newly exportable grids result in a good-looking excel file.

**Comment by lbwexler** [comment]
I do think this protects us somewhat from developers reporting casually that "Export is Broken" when they haven't really thought about setting up export .  Happy to change if you feel strongly about it ATM, but inclined to leave as is....
