### ISSUE TITLE
XH.prompt initialValue does not work

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#1298]
The `MessageInput` typedef doc refers to a `initialValue` prop being supported, however `MessageModel` is only looking for a `value` prop on the `input` config, and it is setting it to the `defaultValue` prop on the field config for the `FormModel` which it creates, which is also the wrong property.

It should be changed to `initialValue` in all places.

**Comment by cnrudd** [comment]
Looking through the develop branch, it looks like the only remaining fixes needed are:

to change this line:
https://github.com/exhi/hoist-react/blame/741c70fdd1850437331182fe572278203aaf55d4/core/appcontainer/MessageModel.js#L63

from:
```const {value, rules} = input;```
to
```const {initialValue, rules} = input;```

and to change this line:
https://github.com/exhi/hoist-react/blame/741c70fdd1850437331182fe572278203aaf55d4/core/appcontainer/MessageModel.js#L67 

from:
```initialValue: value,```
to
```initialValue,```

Does that seem right?

**Comment by haynesjm42** [comment]
Yep looks correct to me, noticed it on 25.2.0 where `defaultValue` was being used so looks like we are already halfway there!

**Comment by nadkarniarjun** [comment]
Agreed. Then we're using initialValue across all consistently.

**Comment by amcclain** [comment]
I fixed the assignment within the actual FormModel to get `value` working, but didn't notice that the typedef was specifying `initialValue`, which I think is better all around.

I will update now to `initialValue` consistently, including the one usage I know of.  I will add a breaking change note to the CHANGELOG as, while this brings the API in line with the docs, it will break any existing usages.

Thanks for noting.
