### ISSUE TITLE
Tooltips in split tree map are constrained by the width of the component treemaps

### ISSUE THREAD

**Issue by inewell** [exhi/hoist-react#1309]
If one side of the treemap is very narrow, then the tooltip (which is constrained to the boundaries of that side of the treemap) cannot fully render and its contents are not therefore readable. This may be an issue with tree maps in general, not just split tree maps.

**Comment by amcclain** [comment]
Good catch - give this a try: https://api.highcharts.com/highstock/tooltip.outside

**Comment by lbwexler** [comment]
Closing this -- tom fixed on the branch where this still lives. Thanks guys!
