### ISSUE TITLE
toolbarSep() is inconsistent

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#1323]
We have supported in the past the elemFactory `toolbarSep()`.  For symmetry with the actual JSX component, this should be `toolbarSeparator()`.   We should either remove the abbreviated usage, or embrace it, e.g. with `appBarSeperator()`.

**Comment by amcclain** [comment]
Resolved (right?) in f1df904a3ae69e4b893c728df3fdad4097648646
