### ISSUE TITLE
DataView sort order ignored when replacing data

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#1337]
In our DataView, the best practice is to pass it a presorted collection of data (it can't leverage ag-grid's sorting like our grid can)

This works fine for the first load, however, on subsequent loads with a different sort order the displayed order doesn't change. A cursory glance suggests this is a regression introduced by the recent Store efficiency improvements to reuse records.

**Comment by lbwexler** [comment]
We intentionally did this, but did not consider this use-case

**Comment by TomTirapani** [comment]
We could consider changing the DataView api so that you can specify a sorter - if set, it will use this field for the single grid column and apply the sorter. It doesn't really matter what field that column uses, since the item renderers are expected to use the whole record anyway

**Comment by lbwexler** [comment]
Maybe I am missing something, but it seems like the lack of a sorting API on DataView is already quite problematic. 

Also, while we are cleaning up DataView, shouldn't it be promoted to be a mobile component as well?  The only thing that would not work is the ContextMenuFunction, and that could simply be documented as a desktop only feature.

**Comment by TomTirapani** [comment]
> Maybe I am missing something, but it seems like the lack of a sorting API on DataView is already quite problematic.

Fully agree. The reason we don't support sorting is because in our grids we are relying on ag-grid to do our sorting. This introduces the limitation that you can't sort by a field unless that field has a column. Since our dataview is effectively a single column grid, it makes using ag-grid sorting problematic. Did you see my comment above about how we can get around this by setting the field on the single column to the sortBy field?

> Also, while we are cleaning up DataView, shouldn't it be promoted to be a mobile component as well? The only thing that would not work is the ContextMenuFunction, and that could simply be documented as a desktop only feature.

Sure, why not. When we introduced the Dataview, our mobile grids were still using Onsen - now we have agGrid on mobile, no reason not to have Dataview as well. It's been a long time since this component got any love! :)

**Comment by TomTirapani** [comment]
Added PRs here:

- https://github.com/exhi/hoist-react/pull/1344
- https://github.com/exhi/toolbox/pull/259

Note that these PRs address adding a sorting API to DataView, but do not include promoting to cross-platform. This is maintain the possibility of releasing this as a non-breaking minor release. Once approved, depending on how close we are to a new major release, we can see if it makes sense to fold this in with the breaking cross-platform change or to tackle those separately.
