### ISSUE TITLE
DateInput picker date/month drop downs behave badly in localDate mode

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1339]
Another weird bug report for everyone's favorite input problem child! Discovered testing a client app, so something we need to fix up if possible....

To reproduce - in Toolbox > Forms - last DateInput example with `valueType: 'localDate'` - open the popup calendar picker, then use the drop-downs to change the year (e.g. 2018, any year).  Calendar switches OK.  Then attempt to use either the month drop-down to select another month (in 2018) or the <> arrows to go back/forwards a month.  Notice that year resets to 2019.

Same issue when e.g. changing the month (via drop-down or arrows) then changing the year via the drop-down - resets to current.

📆 🔫 💥

**Comment by amcclain** [comment]
@febbraiod suggest looking at this along with #1338 - although I admit this one does not look fun. 😭

**Comment by febbraiod** [comment]
I much appreciate the emoticons here. The assignment, well....
