### ISSUE TITLE
Browser requirements / lockout support

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#152]
In Hoist Core we have `io.xh.hoist.browser.Utils.browserSupported()` to match the request userAgent against a configurable list of browser requirements. Need to determine how to translate this into hoist-react world with an independent JS client. 

* Could replicate in part at the nginx proxy layer - https://nginx.org/en/docs/http/ngx_http_browser_module.html
* Could look at libraries or utills that would somehow be included on the page prior to our bundled source (which might include unsupported / not-polyfilled code) that would detect unsupported browsers and do....something...

Pretty big gap as right now a Hoist React app will fail completely and silently if e.g. opened in IE11 - we don't need to make that work, but we need some kind of basic warning in place.

**Comment by cnrudd** [comment]
if (!chrome) document.write('use chrome') will rewrite the document and prevent the script from loading/rendering. 
https://developer.mozilla.org/en-US/docs/Web/API/Document/write
https://developer.mozilla.org/en-US/docs/Web/API/Document/open#Notes

**Comment by amcclain** [comment]
Hi - routing this over to you, Colin.  Would be great to get something in place.

We should think just a bit ahead towards support for mobile access as well where we could use one approach. That might require things to be a bit more complex in terms of a list of browsers or something with the user agent, although I would still be perfectly fine with us have a hard-coded list of what we accept in hoist-react or the dev-utils and not have it be something that we plan to configure or tweak with each app.

My only other requirement would be that the warning message end up appearing reasonable / professional with just a bit of styling to keep with the rest of the framework. But clearly the point is we're not loading the JS toolkits, so I'm just talking about some kind of basic centering, sans-serif font, etc.

Let me know if you want to talk through anything on the dev-utils side as I think that's where this will likely live.  I have been using `yarn link` when I want to test using a local dev-utils.

**Comment by cnrudd** [comment]
starting work on this.

**Comment by cnrudd** [comment]
browser lockout has been implemented by doing feature tests:
testing for support of native Promise (IE11 does not support) and of
Promise finally (EdgeHTML 16.16299 does not support).

This thread(https://github.com/Microsoft/ChakraCore/issues/3520)  suggests that 'finally' support will be coming to Edge soon, so we may want to retest Edge in a few months to see if there are other features we use that it does not support.
