### ISSUE TITLE
Admin - Readme Support w/Markdown

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#153]
Complete TODO Readme panel in Admin application.

Can decide if we want to primarily do this on the client or the server.  Server-side support would have the Gradle/Grails build include the readme as some kind of resource and then potentially parse it and output pre-formatted HTML on a generic endpoint.  The admin client could then call that and display in a "dumb" panel.

Primarily client-side approach would import/include the readme into the client build (somehow) and then use a client-side markdown library to parse and format.

**Comment by lbwexler** [comment]
Closing -- not a priority.
