### ISSUE TITLE
Research paging grid / store

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#180]
We have a need (in both PIQ's orders grid, and in a new client app) for a paging grid / store, or other mechanism, for handling very large datasets. Research ag-grid's handling of large datasets, whether or not server-side paging is required and, if so, best practices for setting it up (ideally with loading new pages as you scroll).

Not sure of the best approach yet, just making this ticket so we don't forget about it.

**Comment by lbwexler** [comment]
John, Tom?  Where are we with the ver large grid in that client app? Do we need more work here?

**Comment by lbwexler** [comment]
Great Tom -- that counts as good research ( and a good outcome).  Closing this -- we will certainly revisit when we need to.
