### ISSUE TITLE
Log level panel needs a delayed refresh to pickup changes to effective levels

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#184]
From ATM: We have an issue I recall from hoist-sencha where you need an additional delayed refresh to pick up the "effective" level...Confusing currently where it seems like your change didn't work, or maybe you don't understand how it works.

**Comment by lbwexler** [comment]
I fixed this in HoistCore -- the log level changes are now synchronous.  This seemed like a more appropriate fix, and was not too hard to make.
https://github.com/exhi/hoist-core/commit/dc387e885bea14b0443
