### ISSUE TITLE
"Toolbox" mini-app to provide easy way to review / test all custom components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#199]
Analogous to the [Kitchen Sink app](https://examples.sencha.com/extjs/6.5.1/examples/kitchensink/#all) provided by Sencha - although no need for anything quite so elaborate.

Will be hosted as a distinct application that is as easy as possible to check out and run. Our goal is also have keep a version deployed for easy reference and as something we can link to from a readme.

Focus should be on components where we have added special handling or extensions that we want to easily verify. *Goal is _not_ to replicate demos or documentation available in the source libraries (Blueprint, ag-grid, etc).*

Items / features we want to include:

- [ ] Welcome panel explaining what the thing is (@amcclain)
- [ ] Standard way to add a sentence or two of explanatory text at top of each tab - not looking to repeat more detailed info in readme or doc comments, but we can probably come up with something minimal to introduce a few components.
- [x] LeftRightChooser
- [x] Load Mask
- [x] Toolbar w/common items (buttons, textfield, combobox, separator, filler, string text)
- [x] Panel
- [x] Core layout containers
- [ ] DataView
- [ ] Grid - flat, boolCheckColumn + cols w/common formatters like date and numbers. Fixed width + flex columns.  Could also have toolbar quick filter
- [x] Grid - grouped
- [x] RestGrid - demo object on server to provide full-stack CRUD example (@TomTirapani will add in server side)
- [x] Resizable
- [x] Icons
- [ ] Charts - line and OHLC
- [ ] Form fields (one tab w/stack of fields - could include LR chooser, also JSON editor, enhanced number field coming soon, tenor field )
- [ ] Dialog - yes we are using raw BP at the moment, but this will likely change and people might look for it in a top-level tab (in addition to encountering it in e.g. the rest grid).
- [ ] Message examples - confirm / alert
- [x] LeftRightChooser - use filter field

**Comment by amcclain** [comment]
Hi - discussed with Lee just now and he suggested building this as its own standalone full-stack Grails app. After thinking it through, I also believe that to be the best plan.

* We can setup the server-side to be very minimal / portable, in particular it can use an in-memory DB so you don't have to have any DB setup.
* It can serve as a decent "hello world" reference on the server side.
* We don't need to work on elaborate mocks or any new devops kind of stuff - can use exactly the same pipelines we have going for the apps.
* It is still a very distinct thing from PIQ, in that we want PIQ to continue to develop as an app we can use for demos, screenshots, etc. that really looks like one of our real apps, whereas Toolbox is a catalog of components and their variations that's purely for development and testing.

Adding @haynesjm42 to this ticket - John can you please setup the base repo and server side, very similar to the other Hello World app you just did?  Gil can then take the client-side code he's been working on in a hoist-react branch and drop it in.

**Comment by gportela85** [comment]
Thanks @haynesjm42, I'll move the code to the new repo once the new `panel` component gets merged into `hoist-react`

**Comment by lbwexler** [comment]
Anybody have any problem with me moving this issue to the toolbox repo?

**Comment by gportela85** [comment]
@lbwexler seems like right thing to do

**Comment by gportela85** [comment]
moved this issue to https://github.com/exhi/toolbox/issues/11
