### ISSUE TITLE
Exception thrown from ensureSvcsReadyAsync() not helpful in production mode

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#206]
We throw a special exception here https://github.com/exhi/hoist-react/blob/develop/svc/BaseService.js#L34 if a service fails to init on startup, where we aim to display the name of the service to the user for troubleshooting.

Unfortunately in minified production code the service (constructor) names are all `t`, which makes this less helpful:
![screen shot 2018-04-25 at 8 39 28 am](https://user-images.githubusercontent.com/225806/39256697-6c4b3f0e-4864-11e8-88f1-6fea8656b13d.png)

Should review options for maintaining / accessing a helpful identifier here, either via our service class or potentially by adjusting the minification options.

**Comment by cnrudd** [comment]
maybe because they all share the same constructor, which is the thing whose name is being shown?
`it.name = svcs[idx].constructor.name;`

**Comment by cnrudd** [comment]
looked into it more.  Same constructor idea is not right.
More likely: when transpiled, the resulting js has the services names as locally scoped function names, which the uglify minifier feels is fine to convert to 't'.

So, maybe the solution lies in some options tweaking here:
https://github.com/exhi/hoist-dev-utils/blob/master/configureWebpack.js#L446

or  here:
https://github.com/exhi/hoist-dev-utils/blob/master/configureWebpack.js#L174

**Comment by lbwexler** [comment]
Well, its a like a 2% increase in size, that we will presumably pay across
the board so not nothin!
But I agree its worth it -- nice find.  Pleas go ahead and make the change

**Comment by cnrudd** [comment]
Ok, i've made the commit directly to master.

**Comment by amcclain** [comment]
Thanks, I think this makes sense - was on my list to look at the mangle options and see what we could tune, and this sounds like the best option for now.
