### ISSUE TITLE
TrackService updates

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#209]
A few cleanups related to TrackService:
* Remove exception from API and service implementation - exceptions should be handled via ClientErrors and not activity tracking.
* Add documentation comments to JS class.

On server-side in hoist-core:
* Add a high-level class doc comment
* Include `severity` as an accepted param track method comment
* Validate / clarify expected values for severity

**Comment by cnrudd** [comment]
Severity could be renamed 'level', as that is most commonly used to describe log levels.  This might free the property of its semantic association with boo boos and other disaster scenarios.

Also, regarding this: "Validate / clarify expected values for severity."  It seems the user building the application might be free to create their own severity values, right?  If we are not using 'severity' in hoist, each new app/client user of the framework could use their own value set.  So, not sure about this.

**Comment by cnrudd** [comment]
By 'Validate/clarify expected values for severity'  do you mean create some constants in JS and in GROOVY like 'OK', 'WARN', ....  or do you mean write in the comments what we want to use?

**Comment by amcclain** [comment]
I suppose if we are going to keep it we should have an enum.  Still not sold on it after the client error work replaced use of tracks for that use case.
