### ISSUE TITLE
Disable spellcheck on relevant Admin editor fields 

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#218]
Clearly not urgent, but still why not? Did not test if supported, but `spellcheck` should be a standard supported pass-through HTML attribute.  Not suggesting we disable by default, but not a bad example to have on these admin fields where we know we are likely entering code-like values.

<img width="408" alt="screen shot 2018-04-26 at 9 17 13 pm" src="https://user-images.githubusercontent.com/225806/39344418-42a88dee-4997-11e8-9220-c7e91f832dab.png">

**Comment by lbwexler** [comment]
👍

**Comment by lbwexler** [comment]
Default is now off for TextFields.  We hypothesize that this is the more common case in our applications for TextFields
