### ISSUE TITLE
RestForm should clear values when datatype changes in "add" mode

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#225]

**Comment by amcclain** [comment]
When adding a new record via RestForm, you can still change the data type, causing the fields to re-render.  As this can cause unexpected values to attempt to be set on fields of different types in unusual ways - and as we are adding a new record and don't have any data we really need to maintain - it seems simpler and more robust to simply null out any already-entered values if the user goes and changes the type in-flight.

**Comment by lbwexler** [comment]
Fixed this here, with addReaction().  Very useful method in this context.

https://github.com/exhi/hoist-react/commit/74497e9cffb2

(cr: Don)
