### ISSUE TITLE
Hoist wrapper for common Blueprint Components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#226]
As part of our ongoing discussions about the role of Blueprint, we'd like to inventory the most common / important direct imports out of our current `kit/blueprint` path and draw up a plan to put Hoist components in front of these. This will provide us a good hook / abstraction layer going forwards to augment (or even replace) Blueprint components as needed.

As part of this, we can determine if we want to do any renaming to more accurately reflect where we think our usage of these components will go - we already have an example of this in [`Message`](https://github.com/exhi/hoist-react/blob/develop/cmp/message/Message.js) and could propose e.g. a `Window` wrapper around Blueprint's `Dialog` (where we add support for things like resizing, DnD, maximizing, etc.).

Some wrappers could remain very thin, functioning to start only as pass-throughs.  For either thin or thick wrappers, we'll need to determine how we want to document the API and if we want to require us to opt-in to BP props or provide a mechanism to expose them all.

I propose that we start by listing out the components we're using heavily here and then prioritize, come up with a plan.

**Comment by cnrudd** [comment]
intellij regex: import \{[^}]*button[^}]*\} from 'hoist/kit/blueprint'
search done in hoist-react:
alert 0
button 34
callout 1
checkbox 1
Classes 3
ContextMenu 0
ContextMenuTarget 2
controlGroup 1
dateInput 1
dialog 10
dialogBody 4
hotkey 2
hotkeys 2
HotkeysTarget 1
inputGroup 3
label 0
menu 1
menuDivider 1
menuItem 2
navbar 1
navbarDivider 0
navbarGroup 1
navbarHeading 1
numericInput 1
omnibar 0
overlay 1
popover 1
Position 1
rangeSlider 0
select 1
spinner 1
suggest 2
switchControl 0
tab 1
tabs 1
text 1
textArea 3
Toaster 1


search done in piq-react:
alert 0
button 2
callout 0
checkbox 0
Classes 0
ContextMenu 0
ContextMenuTarget 0
controlGroup 0
dateInput 1
dialog 1
dialogBody 0
hotkey 0
hotkeys 0
HotkeysTarget 0
inputGroup 0
label 0
menu 0
menuDivider 0
menuItem 0
navbar 1
navbarDivider 0
navbarGroup 1
navbarHeading 1
numericInput 0
omnibar 0
overlay 0
popover 0
Position 0
rangeSlider 1
select 0
spinner 0
suggest 0
switchControl 0
tab 0
tabs 0
text 0
textArea 0
Toaster 0

**Comment by lbwexler** [comment]
Thanks for this useful inventory.  We are going to defer further work here until we have a better sense of our Blueprint wrapping strategy
