### ISSUE TITLE
Standardize on msg vs. message (or support both)

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#230]
This has been a perennial source of confusion / bugs for me for our handful of APIs where we take a config with a "message" parameter.  

E.g. ExceptionHandler takes `message`, FeedbackService `msg`, server-side tracking/error/feedback APIs use `msg`, ToastManager and MessageModel `message`, TrackService `msg`.

Given that msg appears to be baked further into the server, it might be most expedient to standardize on that, but I do think it could be worth it to provide for a fallback on the client-side APIs.

**Comment by amcclain** [comment]
The specific issue I ran into right now was TrackService taking msg, so if we had one change to make I would vote for accepting either there, or switching to message and updating any current code.  That could be done as part of #209

**Comment by lbwexler** [comment]
atm and I both think 'message' makes the most sense here.

Let's just support msg silently, where necessary.  Best not to document that.

**Comment by cnrudd** [comment]
ok, will make sure message is supported everywhere.

**Comment by cnrudd** [comment]
We have decided that we will not accept `msg` in the JS API.  I have removed all instances of it.  The change is in the develop branch.
