### ISSUE TITLE
Panel / PanelHeader component

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#234]
Would like to standardize a simple but popular UI pattern we use of having a div with a header containing a title, optional icon, and a standard CSS class with default Hoist-provided styling.

I think we will want a dedicated PanelHeader component for the header itself. 

Would like to discuss if it makes sense to also offer an enclosing Panel component that would take the same props as the header and auto-create it for you in a vbox layout, while also supporting a dedicated CSS class and additional props (layout direction? disabled?) at the Panel level. 

Would need to think about some special handling for the layout to allow such a component's items to be specified naturally but then pre-processed to sit alongside the header.

I don't want to go overboard in terms of replicating the Ext Panel - i.e. I would hesitate to build in toolbar support, although it's something that could come in time if we thought it would help. Would be happy to proceed incrementally with just a header component we could use to replace a few one-off variations.

**Comment by amcclain** [comment]
@lbwexler would like your thoughts of course re. direction here.

**Comment by gportela85** [comment]
Note: I've been using a h3 element as panel header on the Toolbox app.
VBox example
<img width="513" alt="screen shot 2018-05-01 at 12 48 53 pm" src="https://user-images.githubusercontent.com/7908562/39485380-2bc99fbe-4d3e-11e8-8542-4770c870c40c.png">

**Comment by amcclain** [comment]
That's definitely the general look we are talking about, but I think there would be some advantage to simply using an entirely custom / dedicated class vs. a header element, mainly to avoid an app developer wanting to use h3 headers in plain-old content and/or adding some style on h3 and causing unexpected side effects.  

(I also don't think there's a strong sense that h3 is clear choice for panel headers in terms of some semantic meaning, etc.)

**Comment by amcclain** [comment]
Discussed with Lee some more, and would like to move forwards with this.  I would prioritize this over the Toolbox work (mainly because we want to immediately replace a growing number of ad-hoc implementations in apps with a more standard component ASAP).

Let's go with a `Panel` component as the primary entry-point for apps - we can still end up with a `PanelHeader` comp, but that can be an implementation component for Panel vs. something apps use directly.

It should take the following new props, all optional:
* icon - Icon element to show in header
* title - string to show in header
* topToolbar - toolbar element to show below header and above content
* bottomToolbar - toolbar element to show below content

Other notes:
* There can definitely be more props we can add over time as things evolve, but let's aim to start with a minimal API. The kinds of things we can look at for future iterations could include custom header items, integrating this with the resizer/collapser, using a version to replace the floating Dialog component, etc.
* Let's always create a header even if neither a title nor an icon is specified. If we find ourselves using Panel but not specifying those props and not wanting the header, we can add additional props to control at that time, but I don't want to add them in advance of a real use case.
* Internally, Panel will need some special handling to create a vbox to hold the header + toolbars (if using) and then nest any `items` inside of that. I think that's the thing you get from Panel vs. always doing it yourself. 
* Thought about a prop to specify the internal layout, but Lee suggested not baking that in yet and just letting the developer include a vbox or hbox as the Panel's item if they need multiple children stacked in a particular way.
