### ISSUE TITLE
Add/Delete Preference bugs

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#238]
These are low priority as discussed with Lee:

After creating a new default Preference, if you switch to the User Preference panel to add a corresponding record, the new preference is not available in the User Preference add form without a hard refresh. By the same token recently deleted ones will still be there.

Less importantly, when deleting a default Preference from hoist admin, if you go to the User Preference panel the records for corresponding user preferences are still in the grid but, if you delete one the server will throw because those records were automatically deleted on the server. This is also true in Hoist-Sencha.

**Comment by amcclain** [comment]
Thanks for filing - the first one had been on my mind for a while - also true in hoist-sencha.

Seems like for some of our RestGrids, we would be in a better place if we eagerly reloaded the lookups and the data every time we switched to that tab. For most of these the load times are very fast, it's important to be looking at the latest data all around, and you won't have much "grid state" in terms of scrolling, selection etc. that would be annoying to lose.

That could be the more general "feature" behind this ticket.

**Comment by febbraiod** [comment]
Going to take a stab at this. Already have an idea as to how to handle the eager loading of the grid data, hopefully will figure out how to kick the lookups along the way.
