### ISSUE TITLE
Need a clean way to null out Hoist-added grid colDef props

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#244]
If you have a columnFactory defined like this:
```
const sampleCol = colFactory({
  headerName: 'Sample',
  field: 'sampleField',
  fixedWidth: 100
});
```
where you typically want the column to be 100px wide, but you also want to use it in one special grid where you want it to flex, you might try:

```
sampleCol({flex: 1, fixedWidth: null})
```

But you will start getting a console warning "invalid colDef property 'fixedWidth'" because the code within `fileColFactory` is not cleaning up your fixedWidth config.

We should ensure we always clear out custom configs even if they are falsey or an unexpected value (i.e. for `align`). Should also take a sec to think about any possible meaning for zeros or if there are other override scenarios we should account for.

**Comment by amcclain** [comment]
Agreed I am not too worried about `fixedWidth:0` - it would be a strange choice, although also agree that it doesn't really need to throw or freak out about it.

Mainly just wanted to be able to cancel out a prop set in a colFactory when you have a more specific instance and you don't want that prop to apply.  I think an immediate simple fix would be to just delete all the expected custom props at the end whether or not they are on the object.

**Comment by febbraiod** [comment]
Yep working on that. I was thinking we'd have a top level variable of hoist column props, and, as you said, remove all of them from the object at the end (there's a lodash method for that.) Will PR shortly
