### ISSUE TITLE
Match width of drop-down element to width of DropDownField itself

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#245]
I think it would be an improvement in most cases if the width of the drop-down menu could be matched to the width of the drop-down itself.  Could this be an option?

**Comment by febbraiod** [comment]
Took a quick stab at this. Might turn out to be tricky. The best I could do to control the width of the popOver was to set a width on each menuItem as it goes through the optionsRenderer. If somehow we knew the width of corresponding input field in advance we should use that to match them up, but in the case I was testing the width of that element is flexed (flex: 1 1 auto) as set by pt-fill.

**Comment by amcclain** [comment]
Ah thanks - don't need to mess with anything if it isn't straightforward.  I thought from a quick glance that those popover options might naturally take a width that could be spec'd from any width passed to the field.  If that's not the case, please feel free to close this ticket and we can move on.

**Comment by febbraiod** [comment]
Yes tried that first. Closing.
