### ISSUE TITLE
Mask for disabled / inactive components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#246]
Variant on LoadMask, but without the spinner. 

Could be integrated in forthcoming Panel component via a convenience `disabled` prop there, but also might be useful in other standalone cases for other containers, etc.

**Comment by febbraiod** [comment]
From ATM:

I think it would be very useful if we could integrate into Panel from the get-go via a disabled (or masked?) prop, as I bet that will be the most common case. Could you please look at doing so?
