### ISSUE TITLE
ContextMenu clarification / doc improvements

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#250]
I am a bit confused about the current state of ContextMenu related classes.  I think we need to review the doc comments and class names throughout to tell a more consistent story.

* `ContextMenu` is a Component.
* `StoreContextMenu` is not a component despite seeming like it should be a particular kind of `ContextMenu`. Its doc string is also pretty unhelpful ("...on stores?"). Should it have Model in the name?
* `StoreContextMenuItem` doc string could be a place to introduce the idea that these items get extra info passed to their API
* `ContextMenuItem` also has a `prepareFn` that says it gets selection records?
* Instructions on `ContextMenu` point to implementing `renderContextMenu` but we should clarify that you _don't_ do this for `Grid`. I also think context menus are important enough for Grids the class-level doc comment on `Grid` class should note that `GridModel` specifies the menus.

Talked with you @haynesjm42 yesterday about prioritizing replacing the ag-grid menus with blueprint menus because you have a use case for it.  Also roping you in @TomTirapani with the recent DataView work that tweaked some of this. 

Would either of you be able to take on the task of reviewing this a bit more and proposing some clarifications?  I am happy to help however I can - it's worth getting right as they are important tools, and I think our particular handling of them in Hoist with the records integrations is a really nice feature.

(I know this has been in flux and isn't news that we need some work here - just wanted to create a concrete ticket to ensure we loop back on it - thanks!)

**Comment by haynesjm42** [comment]
I'll take this one on

**Comment by amcclain** [comment]
Largely addressed by #530
