### ISSUE TITLE
Standardize handling of baseCls on Hoist components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#252]
I would suppose a standard `baseCls` property that we define for all our core Hoist-provided components and wrappers.  This should be applied alongside any optional instance-specific `cls` props in a consistent way.

Even if we don't have any particular styling to apply, it is often useful to have a CSS handle on a given component or component-type in the tree.

**Comment by amcclain** [comment]
@lbwexler want to check with you if you think this is a reasonable pattern to apply to all our core components in a consistent way.  Here is the example of what we have in Panel currently: https://github.com/exhi/hoist-react/blob/7e46e916ea0f3aab95fccbffccb595ac6cc6d497/cmp/panel/Panel.js#L43

**Comment by lbwexler** [comment]
This seems like a good idea to me.  Given that 'cls' is built into elem() would we want to build 'baseCls' into elem() as well?  This might allow easier specification of it.  Render methods would not need to this concatenation/ternerary.

Also -- an early implementation of elem() had 'preCls' and 'postCls' to determine how to concatenate.  But that might be overkill.

**Comment by amcclain** [comment]
Cool agreed and let's bring back to elem() - @gportela85 could you pick this one up when you have a chance?  Let us know if unclear.

I don't quite understand the pre vs. post - the order of the class names doesn't have any impact as far as I am aware - was it doing something else I am not grasping?

**Comment by lbwexler** [comment]
Oh boy -- well, not sure what the heck I was thinking regarding the ordering.

FWIW, I did now find this extremely subtle case describing how ordering can matter, but I certainly was not trying to accommodate this minor corner case:

https://stackoverflow.com/questions/15670631/does-the-order-of-classes-listed-on-an-item-affect-the-css
