### ISSUE TITLE
Panel given fixed width/height should not grow/shrink when contained in a flex layout

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#255]
If a Panel is given a fixed size width/height, we should respect that and allow the parent container to scroll overflow if needed.  (Or clip if we need to do that - I think it's more important to keep the contract around the width/height prop.)

**Comment by gportela85** [comment]
@amcclain This might be a complicated issue. Sometimes we want a panel to have an initial height and grow from there if we end up adding panels that make it expand instead of adding a scroller.
We need to decide the wrapper panel should grow or not, and possibly have a config for it.

Maybe we can have a call about it.
Note: Sencha has this config http://docs.sencha.com/extjs/6.5.3/classic/Ext.Component.html#cfg-shrinkWrap

**Comment by amcclain** [comment]
This post gets to some of the issues I think I am experiencing - the difference between not specifying a flex value and specifying `flex: none`.  

https://stackoverflow.com/questions/41772697/flex-none-vs-non-specified-omitted-flex-property

If I add `flex:none` to layout components in addition to giving them the desired pixel width or height property I get the behavior I expected, with less/no layout jitter.

**Comment by amcclain** [comment]
@TomTirapani would you have a chance to weigh in here and offer any advice?  Still think there are some big gaps here in terms of e.g. flex layouts in our panels not behaving as I expect. I can point you to a particular example we could look at.

**Comment by amcclain** [comment]
Closing this with a recommendation to configure components with a standard `flex: 'none'` elem config to be picked up by layoutSupport as-is. This is a one-liner and keeps us aligned with the general behavior of flexbox, which is an API we all need to generally understand and know anyway.

**Comment by lbwexler** [comment]
Sounds great .  Glad you were able to grok this.  Agree about needing to understand flex, and the desire to just stay as close as possible to it.

**Comment by lbwexler** [comment]
👍
