### ISSUE TITLE
NumberField enhancements

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#269]
Looking to super-charge NumberField for our applications. Blueprint has [an example](http://blueprintjs.com/docs/v2/#core/components/forms/numeric-input) with some extended features, but notes they are not part of the core field.

+ Support shorthand entry - 2.4m, 5k, -123b - this is the main one.
+ Render value with commas inserted to help avoid 10x errors. When editing, could not display commas or handle them gracefully (i.e. allow them to be entered but ignore them when ultimately evaluating the input).

BP example also shows support for scientific notation and inline arithmetic. I do _not_ think these make sense for our use cases. 

Will think / suggestions welcome on any other additional behaviors that would be appropriate to consider.

**Comment by febbraiod** [comment]
Also right align numbers in numberField as per ATM.
