### ISSUE TITLE
ComboField - support updates to options prop

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#280]
I would like to have a ComboField where the options are an observable array, so I can push items on the array and have them added as suggestion selections.  (In particular, when a query using the contents of the field returns successfully, I want to add it to options so it will be in the list going forwards.)

However, it looks like ComboField only processes its options once, in the constructor, which creates a new object that's not the observable, so updates to the original observable aren't reflected.

Could we modify to support this use case, or is there another option? Looping in @TomTirapani and @febbraiod as I know you have been working on these combo variants in particular.  Thanks!

**Comment by TomTirapani** [comment]
If you need something quick, you could use a QueryComboField for this right now - an outer component would manage the list of options, and the queryFn would return the filtered list.

But yes, generally I agree all of the DropdownFields should support observable options. I'll take a look at supporting it on the BaseDropdownField level.

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/281

**Comment by lbwexler** [comment]
👍
