### ISSUE TITLE
Update Router5 to 6.x

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#284]
Router5 has released a new major version. As part of our general effort to stay current with our key libraries, would like to review/test/update. 

http://router5.github.io/docs/migration-6.html has info on the update.

**Comment by lbwexler** [comment]
Taking this, as Tom is busy, and I am looking at routing now anyway.

**Comment by lbwexler** [comment]
Just merged this.  Seemed to be a pretty straightforward migration.  I have asked @TomTirapani for a code-review.

We will need to test client apps carefully.  In particular, there have been some syntax changes around parameter usage that we will want to examine in all of our apps. (see link above).  None of the core options should effect us.

**Comment by TomTirapani** [comment]
Looks good - nice that we could lose the HoistMiddleware. I'll check our client apps, making any adjustments for parameter-based routing.
