### ISSUE TITLE
Grid - Component State

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#314]
Building off of the recent merge of column chooser, next step with Hoist-level grid customizations includes support for component state to save user column choices, ordering, and sorting.

I propose an initial goal of general feature parity with the hoist-sencha implementation, ideally re-using the same server-side support in hoist-core with minimal or no modifications. We can push on further than this as we go along to support additional features, but restoring support for basic state is a top priority.

Don - if you could review the [hoist-sencha implementation](https://github.com/exhi/hoist-sencha/blob/develop/grails-app/assets/src/xh/desktop/grid/plugin/State.js) that would be an excellent starting point. We can discuss if we want certain features (e.g. width tracking) to be in or out of scope. Main thing is to grok the complexities around restoring saved state in a safe manner that can cope with changes to columns in the code vs. potentially stale user state.

**Comment by febbraiod** [comment]
Much of what we want is now in place. Reviewed briefly with Lee and made some improvements based on that.

Outstanding items for discussion:

It appears that in Sencha world we only ever made use of the reseting of state functionality in this plugin via the column chooser. Glad to wire that up but I'm not sure if that's outside the scope of this ticket and might be better done in a separate branch after we are happy with grid state handling in general.

Another question is...do we want to worry about column groups? There is a good chuck of code in hoist-sencha surrounding the storing/rehydrating of that. Are we using col groups anywhere now?

One thing I haven't set up yet, but think I am going to take a stab at, is column width. (In the spirit of 'if we can provide that why wouldn't we?'). Not sure how the grid is going to behave with our sort of 'trick' of fixedWidth props, but I imagine I will start be NOT tracking those.

**Comment by febbraiod** [comment]
Wanted to leave myself a note:

As it stands, applying state to the config grid breaks the grouping. State is evil.

**Comment by febbraiod** [comment]
Went over with Lee again today. We decided to punt on columns widths and column groups. Width turned out to be much trickier than I realized and it's unclear that we need to introduce the complexity involved with column groups just yet.

Going to go ahead with resetting state via the column chooser, seems achievable and not so far outside the scope of this ticket.
