### ISSUE TITLE
Validation Support for HoistFields

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#317]
We would like to  sketch out a design for simple validation support in HoistFields.  

Should include a list of the template methods, events, etc. and how an app would use them to modify validation, and how a control writer would use them to display validation.

Note: I do not want to start coding this without a plan. This is a tricky thing to make useful to applications -- very easy to build something that is unusable.

Also, want to keep this as simple as possible, and still have it useful for applications (what else is new :-))

**Comment by amcclain** [comment]
Re-routing to John for now given that he has put together some solutions around this for a particular client application. 

I liked the use of a toast in particular to provide additional details about validation errors in a lightweight way that doesn't interfere with the overall layout of a form.

**Comment by amcclain** [comment]
@haynesjm42 would like to touch base on this next week to see if we can move forwards.  Also want to loop in @TomTirapani as he is planning to build out forms for a client app that will need clear validation status.

**Comment by haynesjm42** [comment]
This may be somewhat larger in scope than what we were thinking for this ticket, but here is what I would propose ..

I took a look at [validate.js](https://validatejs.org/) and it looks like it would be a great library to bring in to handle the actual validation logic. I would see us building a ValidationModel class to wrap up the library similar to what we are doing with RouterModel. The form model/component would create a ValidationModel with the constraints configuration object under the assumption that the attribute names in the constraints match the field names that the HoistFields are associated with (in bound mode, if not using bound mode then it would be entirely up to the app to handle linking validation status to the HoistField components). The validation model would be passed to the HoistField components so they could trigger validation of their field (and only their field) when the value changes. The form model/component could trigger a full or partial validation programmatically based on what makes sense for the form (clicking the save button, etc.). Any ValidationModel methods that perform validation should return a Promise to make sure we allow for asynchronous validations.

The current validation results would be stored in the ValidationModel in an observable field (`@observable.ref results = {…}`) so the owning model/component and the individual field components are able to react to validation status changes as needed. 

For HoistFields I think we should just add a css class based on the current validation results for the associated field. We could provide default styling to add a red border around the input element and allow apps to override it as desired. I think that should be the extent of the styling we apply by default, if anything. We could even just let the app provide the "invalid" css class name to apply in the component props, and do nothing by default.

I would leave it up to the app to display validation messages for individual fields and the entire form in whatever manner they wish (tooltips on the field component, text under the field, in a toast, etc.). We could provide some components for the most common scenarios (ValidationError component which is provided a ValidationModel and a field and simply shows the current validation messages for that field, or nothing when valid. Aurelia provided something similar to this and it made it very easy and standardized to setup form field wrapper components)

Here is what I would expect the standard save button click handler to look like for a form model:

```
onSave() {
	this.validationModel.validate(this).then((result) => {
		if(result.isValid) {
			this.doSave();
		} else {
			XH.toast({
				title: ‘Validation Failed’,
				message: result.formattedMsg
			});
		}		
	});
}
```

Thoughts?

**Comment by lbwexler** [comment]
Thanks for the detailed thoughts on this, especially the pseudo application code, which is *super* helpful!  I think for this project in particular, starting from what the application code looks like is even more important than usual. 

Can we go a little further, and actually write the psuedo code for, say, a form with two fields (e.g. username, password) and a data model, and validation model behind.  What does the model class look like (is it changed at all?).  Where (and how) do I hang my custom logic for determining the rule to be enforced, and the related text output?

**Comment by haynesjm42** [comment]
Here is an example of what I would expect a basic Create User form to look like. I don't think models would need to change at all, unless you want to keep your ValidationModel instance as a member and define the rules there. The validation rules passed to the ValidationModel would just be the validate.js constraints object, which is pretty well fleshed out and highly configurable. I also included a simple example of how I would expect apps to be able to get the validation errors for each field and display however they want.

One nice enhancement you could make to this form would be to add a [custom async validator](https://validatejs.org/#custom-validator-async) which checks that the username is not already in use. We could allow Apps to register their own custom validators (`XH.registerValidator(usernameNotInUseValidator);`) during app init, the validate.js api for setting them up looks very straightforward.

```
@HoistModel()
export class CreateUserFormModel {
    @observable username;
    @observable email;
    @observable password;
    @observable confirmPassword;

    // Imagine there are setter methods for each field here ...

    save() {
        // Send the user create request to the server
    }
}


@HoistComponent()
export class CreateUserForm extends Component {
    localModel = new CreateUserFormModel();
    validationModel = new ValidationModel({
        username: {
            presence: true,
            length: {
                minimum: 6,
                tooShort: 'must be at least 6 characters'
            },
            format: {
                pattern: '[a-z0-9]+',
                flags: 'i',
                message: 'can only contain alphanumeric characters'
            }
        },
        email: {
            email: true
        },
        password: {
            length: {
                minimum: 8
            },
            format: {
                pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\\$%\\^&\\*])',
                message: 'is not strong enough! You must include at least 1 lowercase and uppercase alphabetical character, at least 1 numeric character, and at least 1 special character'
            }
        },
        confirmPassword: {
            equality: 'password'
        }
    })

    render() {
        const {model, validationModel} = this,
            {validationErrors} = validationModel;
        vbox(
            textField({
                model,
                field: 'username',
                validationModel
            }),
            vbox({
                omit: !validationErrors.username,
                items: validationErrors.username.messages
            }),
            textField({
                model,
                field: 'email',
                validationModel
            }),
            vbox({
                omit: !validationErrors.email,
                items: validationErrors.email.messages
            }),
            textfield({
                model,
                field: 'password',
                validationModel
            }),
            vbox({
                omit: !validationErrors.password,
                items: validationErrors.password.messages
            }),
            textfield({
                model,
                field: 'confirmPassword',
                validationModel
            }),
            vbox({
                omit: !validationErrors.confirmPassword,
                items: validationErrors.confirmPassword.messages
            }),
            button({
                text: 'Submit',
                onClick: this.onSubmit
            })
        )
    }
    
    onSubmit = () => {
        this.validationModel.validate(this.model).then((validationResult) => {
            if(validationResult.isValid) {
                this.model.save();
            } else {
                XH.toast({
                    title: 'Validation Failure!',
                    message: validationResult.formattedMsg
                })
            }
        });
    }
}
```

**Comment by lbwexler** [comment]
This is great.  I do think as a pattern, we would want to 'hang' the validation model right off of the main model, rather than the component.  Its really not UI related, and going to be more intimately related to the HoistModel().  

Would be cool in this example to tie the submit button's enabled state to the validity of the model.  That should be easy.  mobx really making a lot of this easy, I hope.

**Comment by haynesjm42** [comment]
Yes very easy, something like `disabled: !validationModel.isValid`

**Comment by amcclain** [comment]
Thanks for this, John. Agree 1000% on using validate.js - I see this as a perfect example of when and how we should reach into the JS ecosystem for a robust and well-accepted solution to this general problem.

I do think we should go ahead and add a dedicated CSS class to invalid HoistField components - probably `hoist-field-invalid` which should accompany a `hoist-field` baseClassName. Would also vote that we setup a default 1px red border invalid style, but with CSS vars to override (and then of course the className for any further customization). That follows the general pattern we'd like to establish of Hoist components working and looking reasonable right "out of the box" (#541).

The example above does show how much extra layout you would need to add if you wanted to show inline validation errors next to each field. Maybe a more scalable approach would be to also supply a `ValidationMessages` component (or something like that) that can nicely format the combined output of a ValidationModel and be added to a typical form in one place. Down the line if we really wanted to we could expand the options for HoistFields to show messages, tooltips, etc. themselves, but I agree it's not clear we want that and definitely don't want to jump into that right away.

Ping me anytime re. your schedule to work on making this real....

**Comment by lbwexler** [comment]
Closing, has been fixed in:

https://github.com/exhi/hoist-react/commit/d019a0605ae301c276cb0c4d1df9d472ead462b9
