### ISSUE TITLE
Implement layoutConfig support for relevant Hoist components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#319]
We added support for `layoutConfig` in https://github.com/exhi/hoist-react/pull/296.

In order to support top-level layout convenience configs, Components must trampoline a layoutConfig prop installed by elemFactory onto their outermost wrapper element.

We should review our core Hoist components (grid, chart, etc) and implement / test this support where it makes sense so you could e.g. specify `grid({flex: 2})` and have the comp behave as expected.

I also see that grid and chart both have custom-looking style blocks in their render that I don't understand.  Would like to review / remove or comment as part of this review:

* https://github.com/exhi/hoist-react/blob/ef9cea3777b746d25de5678fb8241b28507bbe3d/cmp/grid/Grid.js#L83
* https://github.com/exhi/hoist-react/blob/ef9cea3777b746d25de5678fb8241b28507bbe3d/cmp/chart/Chart.js#L34

(there might be more)

**Comment by amcclain** [comment]
Also note that the (common) use of a `frame` as the outermost wrapping element is problematic. That frame elem will [install flex:auto](https://github.com/exhi/hoist-react/blob/ef9cea3777b746d25de5678fb8241b28507bbe3d/cmp/layout/Frame.js#L27) at a point in the elem config processing that will override a custom instance flex config.

We can switch to `box` as an alternate (or if needed `v/hbox`) but then we do lose a kind of "default" flexing behavior if no sizing configs are specified at all. Need to determine if we want that - maybe it is best to have components take their "natural" size and/or look clearly broken to indicate the dev should size it.

For Panel we weren't sure so we added [this custom code to install a flex](https://github.com/exhi/hoist-react/blob/ef9cea3777b746d25de5678fb8241b28507bbe3d/cmp/layout/panel/Panel.js#L59) if not specified - but note it's always using `vbox`.

**Comment by TomTirapani** [comment]
PRs here:

https://github.com/exhi/hoist-react/pull/321
https://github.com/exhi/piq-react/pull/14
