### ISSUE TITLE
Grid sort lost on setColumns

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#324]
I noticed this while working on grid state. However, the issue was preexisting. If you have a grid with a column chooser this is easy to see. When showing/hiding columns on a grid, the chooser sets the columns with their adjusted 'hide' props. If your grid was sorted, it no longer is. Same effect when applying agGrid's column order to 'xh' columns prop on the grid model.

**Comment by lbwexler** [comment]
Don and I solved this one on late friday evening -- It's currently on the following branch

https://github.com/exhi/hoist-react/tree/sortingOnSetColumns

Don will fix up Monday and we will get it in.
