### ISSUE TITLE
Tighten up default 'width', 'height' props on JsonField and TextAreaField.

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#327]
It's not clear from the code (to me) how these fields behave when width is not specified.

**For the JsonField:**
I know from experience (if I remember correctly) that the codemirror library used for the JsonField will try to make the textarea it uses as wide as the container of the textarea if a width is not specified.  But, if a width is not specified, codemirror does not provide scrollbars correctly.
Maybe this info should be put into a comment in the JsonField class, maybe a default width should be provided so that scrollbars always appear, maybe a jsonfield demo or two demonstrating these behaviors should be put into toolbox.

**For the TextAreaField:**
 if the width prop is not provided, there is no default.
After reading the blueprint docs: http://blueprintjs.com/docs/v2/#core/components/forms/text-area
I think it might be worth considering: if no width is provided pass class 'pt-fill' to the blueprint textarea element so that the textarea takes up the fill width of its parent (if that isn't already somehow happening).

**Comment by amcclain** [comment]
Hi @cnrudd  - when you have a chance can you clarify what you mean here by "button down"?  Do we need defaults defined, or need to improve the ones we have?  I wasn't sure from looking at the ticket what needed to happen, or if it was a bugfix / general enhancement / docs issue.  Thanks much.

**Comment by lbwexler** [comment]
Assigning to Colin -- please see ?s by atm

**Comment by amcclain** [comment]
See example in just-reworked toolbox form fields tab - some sizing issues there I don't understand that would be a good test-bed for any changes and fixes.

**Comment by amcclain** [comment]
Also see this patch fix that was required to toolbox - better control over sizing would hopefully avoid need for this: https://github.com/exhi/toolbox/commit/bef7cf8fee9037a24c77b544c3103b99ae260a3e

**Comment by amcclain** [comment]
This is still outstanding - moved the patch referenced above to the component itself after we broke the Toolbox JSX example again - https://github.com/exhi/hoist-react/commit/9906ee4ce9a0a9711166d7f596f5cfd763771dce.

We need someone to sit down and really carefully think through how these fields should size themselves - in terms of the default behavior and the input component API - and then determine how that should be implemented / made possible.
