### ISSUE TITLE
JsonField format key shortcut conflicts with print on Windows

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#329]
On a Windows machine, if I press ctrl+p while in a JsonField editor (intending to pretty print the contents) I get the browser print dialog instead.

**Comment by febbraiod** [comment]
This was an issue with trying to set a dynamic method as a defaultValue in a static context. Lee reviewed, the change is good but it pointed us in the direction of using a createDefaults/getDefaults method to return defaults like this as a better pattern throughout the app. This will help us avoid this kind of problem in the future as well as eliminate the need to split these defaults up in a somewhat confusing way. Will look to make this change as an addendum to this ticket.
