### ISSUE TITLE
Admin LogViewer - autorefresh when in tail mode

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#330]
Lower-priority enhancement but a nice and expected feature when in tail mode is to have the viewer auto-refresh on a relatively frequent schedule to keep showing new log lines.

Should review the implementation in hoist-sencha for any caveats around ensuring the auto-refresh doesn't fight with the user. Mainly we don't want to have it scroll or jump if you have hunted around for a particular line and are in the middle of reviewing it.

**Comment by lbwexler** [comment]
Gil -- can we knock this one off?  Looks pretty straightforward....

**Comment by amcclain** [comment]
Hi - my goodness, just caught me out testing a release here and wondering why in the world I wasn't seeing any updated logs.  I was the one who filed this ticket, but the notion of "tail" is just so ingrained I didn't recall that tailing in current hoist-react admin isn't wired up to anything. 

(Relabelled to bug accordingly.)

@gportela85 I know we have been bouncing you around a bit but I agree this is now a high priority fix - or let us know if you are bogged down and we can re-assign.  Thanks.

**Comment by lbwexler** [comment]
👍
