### ISSUE TITLE
StoreSelectionModel singleRecord doesn't update when record changes

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#333]
The record returned by the computed property singleRecord doesn't change if the underlying record changes. To replicate:

+ Select a row
+ Query the `StoreSelectionModel`'s `singleRecord`
+ Change the record without changing the selection (e.g. make a server side change and refresh)
+ Again query the `StoreSelectionModel`'s `singleRecord` - you'll see the previous record's data.

I think this is because the selection model only observes the list of ids, so only changing this will re-compute the value of `singleRecord`. If this selected id doesn't change, but the record itself does, the value isn't re-computed. From mobx docs:

> Computed values are automatically derived from your state if any value that affects them changes. Computed values can be optimized away in many cases by MobX as they are assumed to be pure. For example, a computed property won't re-run if none of the data used in the previous computation changed.

Noticed in LI where we track the selected record in a dataview and use it to populate various UI components.

**Comment by lbwexler** [comment]
yikes.  this relates to something ATM and I were discussing last week.  It seems clear that the primary side effect of declaring something as @computed is to make a locally cached version of the computed state.  
We were using it -- wrongly I think -- as an API marker that a give getter referenced other observables, and thus was observable.

So it really does need to be "pure" -- and both singleRecord and records are not pure.

A related question is how to then mark getters (or methods) as observable, or transitively observable.

**Comment by lbwexler** [comment]
Actually the specific problem was really with LocalStore maintaining part of its state in a non-observable map.

See:

https://github.com/exhi/hoist-react/commit/6a1d89d4a4715a1169641be3bbc8e8936e2a64ee

Comments regarding @computed still valid -- no *need* to use to make getter "observable".  Main function of it is to reduce thrashing and extra updates by providing a cached "derived" version of state.
