### ISSUE TITLE
Grid - revisit column width / flex configs

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#334]
The current handling of grid column widths is non-ideal, specifically in that there is no easy way to use the (what seems like it should be the most common) `width` config and have that applied as specified as the starting width in pixels. 

I believe this is due to our current workaround to support a `flex` config, where we translate flex into a "really big width" and then are calling `sizeColumnsToFit()` on the grid API to have it do...something...with regard to relative column sizing that kind of looks like flex.

You can use `fixedWidth`, but that prevents interactive column resizing which is non-intuitive and could easily be frustrating/confusing to users. (Ideally fixedWidth would be reserved for special / structural columns, like those with glyphs where there is truly no need / desire to resize.)

If we assume that flex is still important (and I think it is), we might need to look at a deeper approach to adding flex support: e.g. evaluate the grid size, read and subtract the width of non-flex columns, and then compute widths for flex columns based on their flex values / remaining overall grid width (with additional handling for min/max width).  I am sure there are subtleties and this is likely tricky to get right - for instance I've never been too clear on how we handle/consider a flex column that's been manually resized. But I don't think the current setup is going to work for us and the grid is such a core component we need to get it right.

**Comment by febbraiod** [comment]
Started digging into this. Looking at the source of sizeColumnsToFit, I noticed a prop called suppressSizeToFit. It appears that if we set this to true on the column along with a width prop we achieve the desired width on render without preventing an interactive resize.

**Comment by amcclain** [comment]
Adding @gportela85 to this ticket - would like to review when we can with the testing tool you setup, Don, ensure the goals of the ticket are clear, and get Gil started on an attempt at custom implementation for flex support.

**Comment by lbwexler** [comment]
Adding John.  As per #389, this is a priority that he is working on as well.
