### ISSUE TITLE
Checks on errorTrackingService.isReady block error reporting

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#338]
The exceptionHandler and exception dialog both check an `isReady` flag on ErrorTrackingService and, if not true, will silently fail to report anything to the server, including user-entered feedback that the UI still accepts.

https://github.com/exhi/hoist-react/blob/3866e7e2b652d6cf231eaf0f3ccc8c779b9ddf45/exception/ExceptionHandler.js#L94
https://github.com/exhi/hoist-react/blob/3866e7e2b652d6cf231eaf0f3ccc8c779b9ddf45/app/impl/ExceptionDialogModel.js#L36

Does this property exist? Am I missing something with the service lifecycle here or was this from older code that got dropped in a refactor. It's undefined currently when I look in a deployed production app.

Would like to fix pronto.  If we do need some sense of ready/enabled, we should also take care to not accept user input if we can't process/post it.

@lbwexler I'm routing to you right now as not sure who would be best to tackle - happy to take a look myself too, can discuss tomorrow but wanted to file before I let it slip.

**Comment by lbwexler** [comment]
Terrible bug -- fixing this now --- looks like cruft causing a major regression

**Comment by lbwexler** [comment]
Resolved -- good catch
