### ISSUE TITLE
Add Print Icon to our icon collection

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#341]
Some users may want a 'print' button in their app.   Printability of the report the app presents is very important to them.  I found a 'download' icon, but no 'print' or 'printer' icon in our collection in Icon.js

**Comment by amcclain** [comment]
Glyph additions are small enough I think they can go in anytime without a tracking issue here, and can go directly into develop w/o a review (especially when there is a clear mapping of the intended meaning to the choice of icon and there's any need for discussion or figuring out which icon best expresses a new idea).

I checked in a print one for you just now. 😄
