### ISSUE TITLE
Fix Chart component auto-sizing

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#342]
When 3 charts are aligned side by side in an hframe, the expectation is that all 3 charts share the total width equally.  I find instead that the 3 charts are rendered with different widths; 1st one ~ 600px, 2nd and 3rd quite a bit smaller, with large gaps between the charts.

A possible cause of this issue is that the highcharts lib sets its chart's size by looking for a predefined 'width' css value on the chart's containing div.   When it doesn't find this, it defaults the chart's size to 600px wide. 

In an hframe flexbox with 3 chart children, the chart children widths are not specified in code, since the hframe is itself expected to fill an arbitrary width, and the 3 chart children are expected to divide that width equally into 3.

We might look into whether one these libs has already solved this problem:
https://www.npmjs.com/package/highcharts-react-official
https://www.npmjs.com/package/react-highcharts
https://www.npmjs.com/package/react-jsx-highcharts

**Comment by amcclain** [comment]
Thanks for filing - agree this would be a good priority to sort out - ties into our goal of generally getting a better handle on some outstanding layout / sizing issues.

I had not seen before that there is an official wrapper - that seems like a no-brainer to use assuming it's maintained / up to date and doesn't have any blocking issues. But would also be open to looking at the others if they offer any important enhancements over the official one.

**Comment by febbraiod** [comment]
After reading a bit about this problem (we're not alone). I tried using 'flex-basis' in the client demo app to solve this problem and had some success. However, I was unable to reproduce an example in toolbox as of yet.

Here's a link that explains flex-basis:

http://gedd.ski/post/the-difference-between-width-and-flex-basis/

**Comment by febbraiod** [comment]
Client app using Hoist-React ~3.0.0 toolbox at ~4.0.0. Will look to update Client App and figure out how to pass this property with our new layoutConfig asap.

**Comment by febbraiod** [comment]
The issue with specifying flex-basis on a chart instance in HR v4 vs v3 is that in v4 the chart is given a default flex prop of 'auto' which was "winning" over my flex-basis property. 

flex: 'auto' == flex: 1 1 auto

These short-hand props are ordered as such: <'flex-grow'> <'flex-shrink'> <'flex-basis'>.

I therefore set the flex prop on the chart to 1 1 33% for three charts, and viola, even spacing. When demoing this idea to Colin we both short of thought simultaneously that maybe flex: 'auto' isn't what we want to default these chart to. Colin suggested we try flex: 1 1 100%. Which would be conceptually similar to a flex prop in Sencha world. Each item would have a basis of 100% (or flex: '1' in Ext) and therefore be evenly spaced within their container.

**Comment by febbraiod** [comment]
https://github.com/exhi/hoist-react/pull/346
https://github.com/exhi/toolbox/tree/chartFlexDemo
