### ISSUE TITLE
HoistField wrapper for SwitchControl

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#345]
The Blueprint switch control is a very nice alternative to a checkbox in some contexts. I think it makes sense to provide a HoistField implementation of it to match checkbox. 

Does that make sense, or is it somehow not really a form field in the classic sense?

http://blueprintjs.com/docs/v2/#core/components/forms/switch

**Comment by lbwexler** [comment]
I think it makes sense.

**Comment by lbwexler** [comment]
Assigning this temporarily Tom, to keep this together with #359.
(We can also assign both to Gil, if you are swamped Tom)
