### ISSUE TITLE
SelectFields don't highlight current value when expanded

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#362]
If you open a SelectField, the first option is always highlighted, regardless of it's current value. I think it should highlight the currently selected option.

It's not immediately clear if this is an issue with our wrapper, or just how the blueprint select field is supposed to work.

For an example of this, check out the disabledTest monitor in PIQ admin - if you set the value to anything other than Floor, Floor is still highlighted when expanding the dropdown.

<img width="522" alt="screen shot 2018-06-08 at 15 56 32" src="https://user-images.githubusercontent.com/3017757/41165185-eda0b0a0-6b34-11e8-8458-48c8a47fcaf0.png">

**Comment by amcclain** [comment]
Looking at the code / example, it isn't entirely clear how the popover is supposed to get / maintain the selected value.... 

However the [Blueprint docs example](http://blueprintjs.com/docs/v2/#select/select-component) is somehow maintaining selection in the popover, at least if you leave `resetOnSelect` and `resetOnClose` both off. Enabling either of these makes the example behave like our instances, although in our code we are not explicitly setting these flags, so there's still some mystery here.

**Comment by TomTirapani** [comment]
This is a tricky one.

I tried explicitly setting `resetOnSelect` and `resetOnClose` to false, but it didn't seem to have any effect, as you might expect.

I went through the Blueprint source and it seems the `activeItem` is a bit of internal state used within the component, that should be being set internally whenever the user changes something - unfortunately, I'm not sure why it isn't working:

https://github.com/palantir/blueprint/blob/179bdeffff186319cab0adf53596dcdf45a7f04c/packages/select/src/components/select/select.tsx#L110

However, as fully private state, there's no way to make this controlled, which I think could cause issues with our use of controlled value. One could imagine the value changing in the model and the active item still being set to the last item you clicked on.

I pushed a potential approach where we bypass the internal `activeItem` and override it at render by comparing with the controlled value:

https://github.com/exhi/hoist-react/tree/dropDownHighlights

This way, the highlighted item is controlled via the model rather than the select fields internal state, which I think is more correct and will be less surprising.

**Comment by febbraiod** [comment]
Tom's solution looks close to me. I seem to recall controlling the activeItem state via the modifiers.active prop and setting it via the itemRenderer in some (much) earlier iteration of the selectField.

However, as it stands in this branch we lose the behavior by which when opening a fresh select field the first item is selected, allowing us to key through the options. I think I can fix this be simply not using Tom's fix if there is no external value. IE allow the field to continue with it's previous behavior.

We push and open a PR in the interest of revisiting and possibly closing this ticket one war or the other.

**Comment by febbraiod** [comment]
As previously mentioned this is tricky!

I modified Tom's solution to preserve the previous behavior of highlighting the first item in the list if we do not yet have an external value. This allows keying through the options as before Tom's change.

A continuing problem is that the manual setting of the active item seems to also break keydown browsing of the items. This is because on the key down the itemRenderer runs again for each item and we once again set the active item to the external value. Working on this problem now.

Update: Tried to fix by completely taking over the management of the active item on keyDown ('arrowUp' and 'arrowDown'). Ran into trouble with blueprint's internal state, specifically, the options renderer would not run on 'ArrowUp' because even though we are making it appear as if the active item was further down in the list, as far as blueprint was concerned the active idx is 0 when we first open the menu. :(

**Comment by amcclain** [comment]
See https://github.com/palantir/blueprint/issues/2784

**Comment by febbraiod** [comment]
It appears that the blueprint update that I am working on solves this problem. Will continue to update this ticket as needed

**Comment by febbraiod** [comment]
Wanted to note that for reasons yet known the update seems to fix this in the toolbox example but not in our admin rest forms. While investigate but wanted to note so that we don't get ahead of ourselves.

**Comment by lbwexler** [comment]
Why is this still open??  This is totally obsolete due to our new Select boxes. Yea!
