### ISSUE TITLE
Grid - context menu does not highlight menu items when mousing over in light theme

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#370]
This issue is easy to reproduce on any AG Grid.  
Make sure you are viewing the Light Theme.
You can go to the admin -> config and right click on the config grid.   Move your mouse over the menu, and the menu items do not get highlighted.

If you are in the Dark Theme, the menu items do get highlighted.

**Comment by febbraiod** [comment]
This is because our --xh-bg-alt var in the light theme is the same (or very nearly the same) as the highlight-color (which I think comes from ag-grid). Probably best to over ride the highlight color in some way as so many components share --xh-bg-alt.

**Comment by lbwexler** [comment]
Gil -- can you take a look at this, and maybe have Don review?

Thanks

**Comment by lbwexler** [comment]
Just checking back in on this one.  Gil can you look at with Don?

**Comment by lbwexler** [comment]
Any progress on this one?  Gil - can we prioritize this one for the next few days?

**Comment by TomTirapani** [comment]
Reviewed Gil's change - using `--xh-bg-highlight` for active menu items solves the problem, and allows us more control over the menu highlight color for client apps.
