### ISSUE TITLE
Build FeedbackDialog and FeedbackDialogModel into XH

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#379]
It seems weird that these are provided by Hoist, and the underlying service they rely on is provided by Hoist, but we don't wire them into XH by default.  

Seems like if we think its a core part of the framework, there ought to be a one-line way for any app to display these.  e.g. XH.showFeedbackDialog().

**Comment by amcclain** [comment]
As well as a standardized feedbackButton and built-in appBar support pls!
