### ISSUE TITLE
TabContainer should have layoutSupport enabled

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#391]
2 Pieces to this

1) TabContainer should have layoutSupport:true
Useful in general as per our standard for core Hoist comps, but in particular we will often have top-level app tabContainers wanting a flex:1 in the overall layout. Should look for any current apps nesting a top-level tab container in a frame to get this effect and clean that up.

2) switcherPosition should be moved from TabContainerModel to being a prop on TabContainer. 
This has no effect on the state -- its purely a layout related concept.

**Comment by lbwexler** [comment]
John -- just want to touch base and see if we can bang this one out?

**Comment by lbwexler** [comment]
John put this together in a branch -- I am still reviewing and potentially looking to refactor a couple of TabContainer things.
