### ISSUE TITLE
Add XH.isLocalDevelopment

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#399]

**Comment by amcclain** [comment]
I think this makes sense.  Ironically I had this in place when first setting up the webpack builds and configuration of those XH constants via the define plugin, but removed it when baseUrl, etc. became more configurable.

Believe we would do this here in dev-utils:

https://github.com/exhi/hoist-dev-utils/blob/82d45641a1f9016c720e5e3a73a19322b4520e3f/configureWebpack.js#L216

and should be the value of `!prodBuild`.

**Comment by febbraiod** [comment]
Yep pushed exactly those changes yesterday just before I left so didn't issue PRs yet. Glad I got it right 
:)
