### ISSUE TITLE
Exception details reporting dialog maintains user entry across multiple appearances 

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#402]
Looks like we have some model state we're not cleaning up as expected. 

+ Trigger an exception via `XH.handleException()`
+ Show details and enter / submit a message
+ Trigger another exception and show details again
+ Your prior message is still there

**Comment by lbwexler** [comment]
Taking this one since crudd going on vacay, and looks like easy fix, and kind of ugly

**Comment by lbwexler** [comment]
Fixed here:

https://github.com/exhi/hoist-react/commit/0278cecf459ed6
