### ISSUE TITLE
Hoist wrapper for Blueprint Button

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#406]
I know we've raised similar issues before, but at this point I would still like to get a basic wrapper around Blueprint's button. 

This is almost certainly the most basic / bread-and-butter component that you still need to import from kit directly, and the presence of our `cmp/button` package with various more specific button components only makes it more mysterious in terms of getting oriented to the framework and what's there.

**Comment by febbraiod** [comment]
+ use throughout app(s)
