### ISSUE TITLE
Grid - Column Chooser enhancements(alpha sort, built-in search)

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#415]
The alpha sort was requested by client for available columns.  Note that displayed columns should always show up in order of appearance in grid.

Also finding that really need the built-in search for it to actually get used in practice.  Let's throw it in a toolbar.

**Comment by amcclain** [comment]
We have support for grouping columns within the chooser, although it (like all of our custom column configs) is poorly documented.  https://github.com/exhi/hoist-react/blob/69bcd4e692cdf734f881316e0ac308c94e030920/columns/Utils.js#L14

**Comment by amcclain** [comment]
To confirm - ask is to alpha sort available cols (within groups if groups used)
Should also build in column searching - we have a add-on comp I think but it should be out of the box

**Comment by lbwexler** [comment]
Agree would be nice to make this out-of-the-box.  Its gonna take a bit of vertical space, but as long as space is only used when feature enabled, what do we have to lose?

**Comment by lbwexler** [comment]
Giving back to Gil, who originally built this component
