### ISSUE TITLE
Add 'poll' method to our native promise extension

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#422]
I have had to write a method twice that polls an endpoint until that endpoint returns a 'done' response.
I used our promise timeout method to set a timeout for how long to wait for the 'done' response.

After discussing with Lee, we feel that adding a 'poll' method to our promise library could be useful.
It would take the following parameters:
interval
function (promise) to run on specified interval
timeout
timeout message

True, polling can be replaced by subscribing to push notifications.  But not all server apps will have a push service running, and instead expect to be polled.

**Comment by lbwexler** [comment]
Think this is a great ticket.  To be more specific,  think it should be of the following form

poll(interval, timeout, fnAsync)

But how should fnAsync() indicate both that we are done, and what the ultimate results of poll should be?  Also, can it short circuit the entire calculation for an early rejection by, say, rejecting?  Would like to do this all in one function -- not easy!!!

1) We could have null return indicate  "not ready yet", but that would preclude poll() effectively returning null as its ultimate result.  

2) We could have a rejection signify "not ready yet", but that would be a lot of throwing in our "happy path", and would also leave us no way to easily force a reject, if we know that we cannot provide an answer. 

3) We could have a special constant, say poll.CONTINUE, or poll.NOT_READY that should be returned to indicate the result not yet available.  Rejecting would end the procedure with an early reject.

4) We could have it return an array of (up-to)  two results, the first being a boolean flag as to whether it is finished, and the second being the actual resolution, if it is finished.  An early reject could be triggered by an exception returned as the second argument, or a rejection.

The most likely case is that the underlying call is an ajax call -- one question is how do we *typically* want to handle exceptions in such a call.  Ideally we want most applications not to have to specify extra try/catch blocks in their fnAsync

**Comment by lbwexler** [comment]
I added this ticket, but now would like to close.  Its a cool idea, and would be fun to bundle up next time we need it for an app.  But its way too app specific and complex for our very simple low-level promise library.   We should incubate in the real world first.
