### ISSUE TITLE
Update NumeralJS to NumbroJS

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#425]
This library is possibly EOL. Last commit was in March of 2017.

Ran into a bug regarding numbers with exponents of -7 or less. This turned out to be a known issue that was reported about a year ago along with a PR to fix. Apparently there has been no response from the author:

https://github.com/adamwdraper/Numeral-js/issues/512

There seems to be some indication that rolling back to 2.0.4 (we're at 2.0.6) might fix the specific problem but we're not sure what we might lose in that case. Lee and I discuss a workaround for our client problem, but want to have a ticket to track in case this going to be an ongoing issue.

**Comment by haynesjm42** [comment]
Ran into this exact same issue in a client app, and put a workaround in place.

Numbro looks pretty solid, and seems to be what other are moving to from numeral.js. Could possibly just be a drop-in replacement using the string format (http://numbrojs.com/old-format.html)? 

And of course a big +1 for the adorable logo.

**Comment by amcclain** [comment]
Thanks for letting us know that you ran into the issue as well - that's a key indicator that this is not a one-off. Was the workaround something that could be generalized or was it very specific? Is it something we will run into again if we switch the Hoist formatter implementation?

Sounds like we should continue to keep this active and on the list. I would vote for not starting out via the "old format" method, but instead look to use their latest / recommended API. A breaking change related to supporting the string format argument only would not be too bad, if we were supporting all the other flags on our number formatter the same...

**Comment by lbwexler** [comment]
interesting that numbro is a fork of numeral.js -- hadn't realized that.  I think we should rename this ticket and will do so as the direction forward, if we take it seems clear.

**Comment by haynesjm42** [comment]
My workaround was very specific, and was just to avoid getting `NaN` in grid cells where the value was exponential and had e-7 or more (less?).  In this case the actual values are extremely small, so I am just changing them to `0`. Very specific and intended to be temporary until this issue is resolved.
