### ISSUE TITLE
Make loadMask text dynamic

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#426]
In a client app, I used a single loadMask for successive api calls and updated an observable  loadMaskText property on a model based on the call being made or based on a status being returned by the server. I fed that into the loadMask via the render method on the mask's parent component. When that prop changed the loadmask rerendered with the new text.

Lee thought it was a good move and should be built into loadMasks. One way of doing this might be to put an observable loadMaskText prop on our LastPromiseModel. A LoadMask could check its bound model for that prop and use that, before defaulting to it's own text prop. Applications could then dynamically set this prop on the LastPromiseModel. Lee also thought we might do this via a ref on the mask itself. Open ticket for discussion.

**Comment by amcclain** [comment]
The PromiseModels don't currently have any direct connection to a LoadMask or any specific UI concept within their own class (and I think that's a good thing).

Given that, it seems a bit weird to have a config as specific as `loadMaskText` be part of the model API, but I also understand why it makes sense to have a dynamic message on the model. That's the object the owning component / model is managing and linking to a given operation.

Would a slightly more generic name for the PromiseModel property help, or just confuse things? Thinking something like `pendingText` or `pendingMessage` or just `message`.

**Comment by amcclain** [comment]
Resolved via d00a5c6e8fc1e0e89c2ce3eef5f3e14cb842f3c8.
