### ISSUE TITLE
GridModel's setGroupBy method should handle multiple levels of grouping

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#430]
Based on request for client app

**Comment by amcclain** [comment]
This sounds like it could be more a "tree grid" vs. a "grouped grid".  Does this multi-level grouping use case expect there to be cell-level values for the grouped rows, or just nested grouping headers (without values)? Trying to think if I've seen examples of multi-level-but-not-tree grouping.

(Overall tree grid API and design still pending as a high-priority TODO regardless)

**Comment by febbraiod** [comment]
The request was for grouping as I was sent a code example of an angular app using ag-grid grouping to accomplish what they were asking for, which is how I figured out they didn't want a pivot table which was the original ask(long story).

I have since been asked to put an aggregate value in the group row. In any case, we have a separate ask that was described to Colin and passed on to me that very much sounded like a tree grid so it looks like we'll need that soon either way.

**Comment by febbraiod** [comment]
Closing in favor of tree grid ticket
