### ISSUE TITLE
Upgrade to mobx 5.x

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#431]
Note that mobx 5 uses proxies -- will this work for our mobile browsers?

https://caniuse.com/#feat=proxy

**Comment by amcclain** [comment]
Hard to say - I am not positive which version of Safari best correlates to the UI WebView used by non-standard secure browsers (if there really even is one that maps onto caniuse).

A good reminder that we need to check in general how the current mobile setup performs on device. We should have a deployed snapshot version soon of our current project that we can test.

**Comment by lbwexler** [comment]
Assigning this to Tom -- Tom was just going to confirm that all works well with the particular Mobile browsers at a Client site.

**Comment by lbwexler** [comment]
Tom tried this out, and it worked fine with our mobile apps at client with legacy mobile browsers.  We are going to keep our eyes out for issues...
