### ISSUE TITLE
TabContainer - pref support to remember last visited tab

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#447]
Need to make sure it works with RouteForwarding and route enabled tab containers as well.

**Comment by amcclain** [comment]
I still think this could be a useful feature and is worth folding in at some point.

That said, closing and tagging as a future project as IMO the potential interaction with and complexity around routes throws off the cost/benefit calc. Of course if we've seen further evidence that this would clean up / aid application code, we can reconsider!
