### ISSUE TITLE
Grid multi-select right-click behavior

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#464]
In multi-select mode, when right-clicking on a row, it is appending it to the selection instead of clearing the existing selection and selecting only the right-clicked row. With the current implementation you can just keep right-clicking rows to continually add to the selection.

Not sure exactly what the expected behavior should be here, and whether we should be supporting SHIFT and CTRL selection on right-clicks, but seems like the simplest approach is just:

IF right-clicked row is part of current selection, show context-menu with no selection change
ELSE IF right-clicked row is not part of current selection, select right-clicked row and clear other selection, then show context-menu.

**Comment by lbwexler** [comment]
This approach makes good sense.   Agree that we could potentially allow SHIFT and CTRL selection, but that really is an extra-nicety, and not really sure what is expected there.  For now user can arrange their selection with left-click, and then when ready to go, operate on it with a right click.
