### ISSUE TITLE
Remove mobx-decorators dep + unwind usages of @setter

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#483]
The mobx-decorators library (https://github.com/farwayer/mobx-decorators) has yet to be updated to officially support MobX 5.  The repo does not currently contain any more info about issues or planned support - no issues/PRs, etc - only a one-line note in the readme saying v5 not yet supported.

We are using it successfully with MobX 5 at the moment - in practice we are only using the `@setter` decorator, and we confirmed that does work.

However given our minimal usage and now doubts about the maintenance of the add-on library, we think it's worth removing the dependency and replacing any usages of the decorator with explicit `setFoo()` methods as needed. This removes one more piece of magic from the toolchain and focuses us more narrowly on the core MobX offering without confusing things.

It will also remove a current warning during the Webpack build re. the incorrect peer dependency.

**Comment by lbwexler** [comment]
Tom -- let's go ahead and do this.  I think best to stick with the creation of a setXXX method where need it.  Its an "action" and I think that the use of a javascript setter for a mobx action is way too subtle.  We are trying to draw attention to these state altering methods!

But let's also be cognizant of:

1) Whether its "public" or "private" and seek to put the privates below the implementation block.
2) Whether we really need it.  In particular, if its just being used privately, can a private calling method simply be made an action?
3) All model fields that are bound to HoistField will need this.  These won't be found by 'setXXX' searches....

**Comment by lbwexler** [comment]
👍
