### ISSUE TITLE
DayField - with commitOnChange=false, selected date does not appear in input field

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#497]
With commitOnChange=false (which is the default), when clicking on a date in the popover, the selected date does not appear in input field after the popover closes.

**Comment by febbraiod** [comment]
Perhaps as part of this ticket dayFields should be commit on blur by default but the render value should change when selecting from popover

**Comment by amcclain** [comment]
This seems similar to the editable select field in some ways - we don't want to try to commit partial values if you are typing in a value manually, but selecting from the popover is a "complete" action and should immediately commit the date.

(I think that's exactly what you are saying here - i.e. commitOnChange remains false but additional handling is added to ensure the popover selection goes in right away.)

**Comment by febbraiod** [comment]
Looks like we already had an affordance for this. Blueprint just changes their API. There is no longer a popOverWillClose prop. It's not onClose. Will push fix shortly.
