### ISSUE TITLE
VBox doesn't size children according to relative flex values 

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#506]
See example in the Toolbox https://toolbox-dev.xh.io/app/containers/vbox

**Comment by febbraiod** [comment]
The change to the demo was made in toolbox, with plans for a better resizable demo. Our boxes are behaving according to the css flexbox behavior. There was some discussions as to how we may want to adjust our wrappers to handle flex values in a more intuitive way such that the ratios between flex'ible' container is respected exactly (i.e. not first factoring out padding), but I think that is outside of the scope of this ticket. Closing.
