### ISSUE TITLE
Add tooltip support to Column API

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#509]
The ag-Grid [column API](https://www.ag-grid.com/javascript-grid-column-properties/) supports `tooltipField` and `tooltip` options for specifying a built-in tip that should appear on a given cell.

Review for inclusion in top-level Column class API, supporting either both or just the function variant (to allow for formatting) and reviewing/normalizing the signature for the function.

**Comment by amcclain** [comment]
Would like to propose adding `tooltip` as a unified top-level config to the Column constructor API, taking one of:
* boolean - true to output cell value directly, useful when all you are worried about is truncation. I think we would need to use the raw value (vs. running through any renderer that might also be provided) so tips don't need to support HTML...
* string - field name to output - equiv. to ag-Grid `tooltipField`
* function - suggest we match the renderer API (instead of ag-Grid) `tooltip: (v, data, meta) => {}`

Note that for numbers, the tooltip functionality built into the number formatter might be a better option, especially if we improve via #434.

**Comment by lbwexler** [comment]
Wonder how frequently we would really want option 2 (a completely unformatted second field).  Would it be easier to just have users write tooltip : (v, data) => data.tooltipFld.    

Tips won't support any html?  That's a shame -- we need to be careful with this.  We don't really have any guarantees that any of our formatters won't return html.  (e.g. just adding a units label to a number creates a span)

**Comment by amcclain** [comment]
+ Agreed re. not needing to support string arg for alternate field (does seem rare)
+ We should research if ag-Grid's tooltip implementation can support HTML in tooltips.

**Comment by amcclain** [comment]
Resolved in eee14d6819a1a6b0f3462551d02f52ad30dc11ef
