### ISSUE TITLE
Unable to change dates via controls in Admin activity grid toolbars

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#513]
Attempting to change the date ranges in the admin tracking grids via the date-picker pop-ups leaves the values unchanged.

**Comment by cnrudd** [comment]
The person working on this ticket should first see if resolving this ticket:
https://github.com/exhi/hoist-react/issues/497
solves this ticket.

**Comment by cnrudd** [comment]
Once #497 and this ticket are resolved, it might be convenient to also look at: https://github.com/exhi/hoist-react/issues/502

**Comment by febbraiod** [comment]
+client error dayField
