### ISSUE TITLE
Ensure className applied after ...rest props destructuring for baseClassName support

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#521]
An example of this is Toolbar, which breaks if you give it a custom `className`.

By default, Toolbar uses an hbox internally, and uses `baseClassName` to end up with `xh-hbox xh-toolbar`. If you give toolbar `className: 'foo'`, you would expect the final class to be `xh-hbox xh-toolbar foo` - instead `xh-toolbar` gets lost and you end up with `xh-hbox foo`.

**Comment by amcclain** [comment]
Components that wish to a declare a `baseClassName` while also spreading ...rest props to their outer render element must apply the combined class list after spreading all other props. 

🐞 INCORRECT - combined className will be overwritten if supplied in props
```
render() {
  childPanel({
    className: this.getClassName(),
    ...this.props
  })
}
```

👍 CORRECT - className will include baseClass from comp/parents + props
```
render() {
  childPanel({
    ...this.props,
    className: this.getClassName()
  })
}
```
