### ISSUE TITLE
Improve grouped rows display via ag-grid

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#523]
Grouped rows in ag-grid's examples are indented. Seems like something we should be able to control via their API. Once this ticket is resolved, remove .xh-lr-chooser__group-row  class from lr chooser.

https://www.ag-grid.com/javascript-grid-grouping/

**Comment by amcclain** [comment]
Closing as lower priority - we know we can apply a dedicated style if we have a grid (like LRChooser) where we know we want it.
