### ISSUE TITLE
Support column grouping in grids

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#539]
As per client request as well as a natural feature for us to support.

As per ATM:  Need to ensure it plays well with the sync between grid<>model as well as persistent grid state.

**Comment by amcclain** [comment]
Another key next step for Grid API. As per our Slack chat, areas of focus will include:
* Reviewing the overall ag-Grid API/story around column groups
* How this would interact with our code to sync grid component state back to the controlling GridModel
* Interactions with column sizing / flex
* Interactions with persistent grid state (column ordering)

**Comment by amcclain** [comment]
Hi @cnrudd tagging you on this ticket as well - understand this is a priority, hoping it is something we could make progress on next week all together.

**Comment by amcclain** [comment]
👍 on setting/enforcing the (terribly named!!!) `marryChildren` option to block moving cols out of groups. This was a common setting we used in ExtJS world as well (where they were called `sealed` groups).

**Comment by febbraiod** [comment]
Finally got this to work when reacting to user driven state changes. Going to review with Lee shortly.

One question is do we want to invest the time now in supporting gridState (as in local storage) for grouped grids? Or do we want to get the grouping functionality in sooner rather than later and put off support storing/rehydrating grid state?

**Comment by febbraiod** [comment]
Simplified with Lee. He suggests having a look a the state plug in now.
