### ISSUE TITLE
LeftRightChooser options should not be indented if not grouped

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#544]
Appears as if `xh-lr-chooser__group-row` always applied.

**Comment by febbraiod** [comment]
Actually it looks like this is a problem with ColChooser not L/R. Looking at the L/R chooser example in toolbox, I turned off the grouping for the left side and the items appeared normal. The colChooser however has left grouping enabled by default, but doesn't always have a group column to group by.
