### ISSUE TITLE
Grid columns w/renderers don't trigger refresh on non-primary field value change

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#550]
Take a grid column with the following config:
```
{
  field: 'name',
  renderer: (v, data) => v + ' - ' data.email
}
```
The cell should (but does not) update if the `email` value is changed for a given row. 

This appears to be caused by the grid using the `valueGetter()` column property to perform change detection, whereas the Column.renderer API is using the `cellRenderer()` property. See https://www.ag-grid.com/javascript-grid-change-detection/.

**Comment by lbwexler** [comment]
We haven't really intentionally been relying on cell (or field) level change detection. Right now, when we update the data for a grid, we  would be happy to invalidate the drawing every cell.  The only state we are relying on it saving is the focus, scroll, and selection state.

Perhaps we need some more aggressive way to invalidate these cells when we change the "records" observable of the GridModel?  Or adjust the mode we are using for Ag-Grid.

**Comment by amcclain** [comment]
But don't you think that's key to the grid's overall performance? I wasn't assuming that we would be happy always having it re-render every cell on every change, would we? 

Relates to how it works with React - I wasn't counting on its implementation getting the benefit of the React virtual DOM layer...  Let me know of course if I am missing something fundamental here, and we can always look for options and test in the real world.

**Comment by lbwexler** [comment]
We aren't talking about updating individual records in the store in a
streaming situation.  We are actually reloading the whole store, and it is
something that doesn't happen that frequently in our current usage.  (The
most rapidly it happens is probably when wired to a store filter field.).

My understanding was that with Ext, our similar usage pattern of calling
store.loadData() and passing in brand new records was also yielding a full
refresh of all the grid cells, without any sophisticated change detection.

**Comment by lbwexler** [comment]
Well, it does seem like Ag Grid has a very strong bias against cross field renderers like this.  

Tried to turn off change detection via suppressChangeDetection: true and was unable to get that to work.

calling refreshCells() does work, but not clear how to avoid rendering the changed data twice.  But this may not be the end of the world, as most data is *not* changed...

**Comment by lbwexler** [comment]
Actually, am able to get it to work with 'deltaRowDataMode: false', which I think may be just what we want:  
https://www.ag-grid.com/javascript-grid-data-update/

**Comment by lbwexler** [comment]
Closing with https://github.com/exhi/hoist-react/commit/ff598f1135c9
Turns on we really need that deltaRowDataMode to maintain scroll state across the loads.

Forcing a full refresh of all drawn cells is the safest and most appropriate here, and is what we really expected to be happening for a full data reload.
