### ISSUE TITLE
Add selectOnFocus option for relevant HoistField components

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#554]
If true, input field should auto-select its current value when focused, to allow easy typeover of the entire value.

See e.g. [ExtJS TextField config](https://docs.sencha.com/extjs/6.5.2/classic/Ext.form.field.Text.html#cfg-selectOnFocus) - a cursory look at the Blueprint docs did not immediately turn up a similar prop, but a closer look is warranted (or we implement as needed).

**Comment by amcclain** [comment]
I noticed just now that TextField supports an `autoFocus` prop - should confirm if this meets the requirement here / generally works and then review which controls support it.

https://github.com/exhi/hoist-react/blob/develop/desktop/cmp/form/TextField.js#L29

**Comment by nadkarniarjun** [comment]
The `autoFocus` property does not auto select on initial render. It simply gives that element first focus when the page is rendered. 

I am looking into implementing the original `selectOnFocus` property.

**Comment by amcclain** [comment]
Great thanks! Let us know what you find - will definitely be put to quick use.
