### ISSUE TITLE
ExportFormat support for "long text" with wrapping

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#555]
Use case is a grid where some fields have longer text strings - a few sentences of notes, say. 

Would like to be able to specify an `ExportFormat` code that would cause an exported Excel sheet to wrap the text and apply auto row-height mode so all text is immediately visible / printable within the cell. 

Have not yet reviewed current default behavior - or verified that this is possible given Excel / Apache POI functionality. It seems reasonable, however, and in particular could make Excel exports a more attractive option for printing support in some particular cases.

**Comment by lbwexler** [comment]
Adding Tom, who has the experience with this.  Hoping Tom can help guide Brendan on this one.

**Comment by TomTirapani** [comment]
Hi Brendan

Haven't tried it yet, but looks like a good start :)

How does this handle auto heighting the row to display the full wrapped text? Again, haven't tried it, but it looks like calling `row.setHeight(-1)` on each row after we've added the content could do this for us (unless we already have that behaviour by default). [Docs](http://poi.apache.org/apidocs/org/apache/poi/hssf/usermodel/HSSFRow.html#setHeight-short-)

Feel free to reach out if you have any questions or want to go over anything.

Cheers
Tom

**Comment by shravnk** [comment]
Hi Tom,

I've not been able to set auto height with setHeight(-1), though it does work for positive values.

setWrapText(true) does auto height, but the default column width is probably too large for our purposes (see output sample below).

I think it makes sense to implement this behavior where the styles map is defined on line 128 of GridExportingImplService. This allows us to only set wrapText on specific columns. We could define a new ExportFormat for a Column e.g. LONG_TEXT, and then set wrapText and a default column width accordingly.

Note that in the branch I created for this issue, wrapText can only be toggled for the entire spreadsheet.

Let me know what you guys think.

<img width="1832" alt="screen shot 2018-09-17 at 10 49 40 am" src="https://user-images.githubusercontent.com/33368494/45631504-03a0c380-ba69-11e8-974c-d765ba76afb9.png">

**Comment by TomTirapani** [comment]
Okay - if `setWrapText(true)` auto heights, don't worry about the `setHeight(-1)` :)

Sounds like a good approach to use a custom ExportFormat to set wrap text and a reasonable default width. Bear in mind that on line 199 we are looping through the columns and calling `autoSizeColumn()` for each - we probably want to skip any column with wrap text here.

**Comment by shravnk** [comment]
Sounds good, thanks. Good catch on the column autosize.
