### ISSUE TITLE
Admin General > Users tab - add "active only" checkbox filter

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#567]
HoistUser interface defines an `isActive` flag. The admin user list grid could add a toolbar filter to show only active users, on by default.

This will be useful in environments where we might load and return a large number of prior users. 

Better I think to have this relay the query back to the server vs. implementing client-side only, although either likely fine in practice for now.

**Comment by lbwexler** [comment]
This should be a pretty quick item -- would love to get this done.  Let us know if any questions...

**Comment by lbwexler** [comment]
👍
