### ISSUE TITLE
Create a self-contained Docker environment for Hoist

### ISSUE THREAD

**Issue by nadkarniarjun** [exhi/hoist-react#576]
We could have both Core and React in Docker containers with a self-creating script, so new devs (and new clients) can get a version of Hoist up and running quickly and easily.

**Comment by nadkarniarjun** [comment]
Still getting up to speed on the current environment here, so I'll give you an example of a previous project where a Docker-ized setup helped:

The environment for that project was pretty complex, in that we had a legacy PHP application layer, a Laravel API layer, a Java / Spring layer, a Redis caching layer, a SOLR layer, and a MySQL layer. Each had it's own idiosyncrasies, e.g. the legacy PHP app required a particular version of PHP, along with specific libraries for that version (ImageMagick, and so on). The SOLR layer needed it's own version of JDK, which was different than the Java / Spring layer. 

So, in the above situation, Docker came in very handy, because we were able to tailor each Docker image to the specifics of what was needed. 

I'm not sure you have all that complexity here, but you do have some dependencies like npm, JDK, etc. Rather than having a new developer install these locally, you could have all of them installed within, say, two containers: one Docker for Grails (with all the JDK stuff), and one Docker for React (with all the appropriate stuff). You could then have a master Docker script that was container aware, that basically downloads and starts up the environment as needed. 

This way, new devs could get up and running in mins, without having to worry about installing anything locally.

**Comment by amcclain** [comment]
Closing this - I think the core pain points this ticket is addressing could be handled by our recent discussions around a "Hoist Central" style deployment, where the server (primary source of dev-environment requirements and complexity) could be deployed to a site as a general service.
