### ISSUE TITLE
Implement FieldSupport based validation within Admin client

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#582]
Several core Admin console forms could benefit from the validation framework provided by `@FieldSupport` (see d019a0605ae301c276cb0c4d1df9d472ead462b9). 

We would want e.g. a soft-confguration entry's "name" field to be highlighted and marked invalid in the standard way if left blank. Any other similar entry forms within the Admin console should be reviewed to determine what real-world validation rules make sense.

(Have not yet looked to see if this will require API updates or similar on the RestGrid and form classes.)

**Comment by lbwexler** [comment]
Closing this.  As discussed with ATM and Tom, RestGrid has a very particular setup here, that is doing the job fine.  Rewriting would be a lot of work with little benefit.  Not a priority.
