### ISSUE TITLE
Standardized app options (user preferences) panel 

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#585]
I think there is room in the framework for a component to help standardize an (optional) component for users to adjust app-wide options.

I am envisioning a panel that's launched via a standard button (gear or similar) from the AppBar and provides some way of specifying a collection of editors that key to Preference keys. The component would do the work of reading the various prefs and setting them (when changed) via PrefService.

The specification of preferences controlled by the panel should also include a flag to indicate a full app refresh is required on change and to alert the user / do the refresh if required.

Clearly we should not be overly limiting about what kinds of options or controls can be managed in this component. It should ideally be capable of hosting controls within nested layout containers and/or having controls that do or display other data not sourced from preferences.

But in general I think this is a common enough pattern and a nice way to reinforce the use / shared nature of preferences that it could warrant a convenience component in the framework.

**Comment by amcclain** [comment]
Another additional aspect of this shared component is that it might prompt us to support some other flags - such as the compact mode for grids - in a way that allows them to be bound to preferences that would then be easily controlled by this panel. 

Theme is another example - an app developer might choose to add that as an option within this panel vs. dedicated a top-level AppBar button.

**Comment by TomTirapani** [comment]
Got back into this:

https://github.com/exhi/hoist-react/pull/818
https://github.com/exhi/toolbox/pull/113

This implementation supports using any of our HoistInputs to either control preferences or any other non-preference values. Devs can specify which options require app refresh. Implemented in both desktop and mobile.

Currently *doesn't* support custom layouts, instead always displaying fields in a list.

**Comment by amcclain** [comment]
As per Lee's comment in the PR, we'll loop back on this once #857 lands.
