### ISSUE TITLE
Reliably generate unique store record IDs as required

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#590]
LocalStore currently will auto-assign an ID to raw data objects if they don't contain an `id` property:

https://github.com/exhi/hoist-react/blob/0416d9413dac37fc6c49256497ee5b2b583d18c9/data/LocalStore.js#L116

This is currently based on the index of the object in the raw data array, and is problematic in a few ways:
+ It mutates the objects passed in to the store (we should be clear if we are OK doing this).
+ Use of raw number does not make it clear that these are locally generated IDs.
+ No check that an ID about to be assigned by idx does not overlap with another ID.  We had a particular use case where we ran a collection w/o IDs through `loadData`. They were mutated and idx-based IDs added starting at 0.  We then placed a new item in the collection at the start of it (code looked like `data = [newItem, ...oldItems]`) and ran through `loadData` again. The new item received an idx-based ID of zero, which was the same as the record right after it (which kept that ID as it had it already).
  + Note this was especially unfortunate as the store was powering a grid, and ag-grid will silently drop rows with dupe IDs.

Discussion items:
1) Are we OK mutating the objects passed to loadData()? Is that simply part of the store contract, or should we either avoid ever mutating or clone then mutate the copy?
2) Should we be auto-assigning IDs automatically at all, or should we instead throw if the objects to be loaded don't have an ID already?
3) Should we support a configurable `idProperty` on the store, so you could tell it to expect e.g. `Id` vs. `id` on the objects? This was a real use-case and has an equiv on the ExtJS side. Might make (2) more agreeable.
4) If we want to continue generating IDs as needed, how best to ensure uniqueness. Each store could have a monotonically increasing `idSeed` value it uses for the life of the store. Or we could have a global one via XH that would be used across all stores or other things that need IDs (again [see Ext example(https://docs.sencha.com/extjs/6.5.2/classic/src/Ext.js.html#Ext-method-id)).
5) And if we auto-generate, do we want to use a prefix such as `xh-id-` to make it clear these are generated locally?

**Comment by lbwexler** [comment]
Hi:  Looked at the implementation and think you landed in a good place.  

It always seemed to me that either all the incoming records should have ids, or none of them, but I never considered the case of feeding existing records back into a store and re-assigning the id.  

Its a good point about whether or not we should be mutating the data passed in to loadStore.  Probably not, but my tree store/tree grid branch fixes that anyway, so no need to rock the boat on this issue now.
