### ISSUE TITLE
Field validator dateIs could take special token for "now"

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#597]
The `dateIs` validator takes min/max params, which are fed dates. 

This could potentially be problematic as those are then fixed when the relevant model class is first constructed. For a client app that remains running for more than a day, it can then be problematic to express a constraint such as "no later than today" as the date that's passed to the max validator will not age.

A bit of an edge case, but certainly a real-world one which we have encountered in the past.

**Comment by nadkarniarjun** [comment]
How about if the min or max argument is equated as now() if the caller passes `undefined` as the value for them? It would keep the method signature compact, but may not be quite as intuitive as adding parameters.

**Comment by nadkarniarjun** [comment]
Nevermind. Spoke with Lee, and he correctly pointed out that you may want to pass in `NULL` for either argument if you don't want to have a min or max. Instead, he suggested to check for the actual string `now`, which is what I'm coding.

**Comment by nadkarniarjun** [comment]
Done! PR submitted.
