### ISSUE TITLE
MultiSelect display bugs

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#614]
See new News example in Toolbox - slightly but noticeably different styling on the two placeholders here:

![screen shot 2018-09-13 at 8 14 27 am](https://user-images.githubusercontent.com/225806/45497644-2cede680-b72d-11e8-9482-d123325f9cbe.png)

Also, having entered a tag in MultiSelect, I see two "x" icons in the tag, and the empty text switches somewhat inconsistently to "Search..." which seems odd.  Would be best I think to not have any further empty text there if we can suppress.

![screen shot 2018-09-13 at 8 19 07 am](https://user-images.githubusercontent.com/225806/45497886-b43b5a00-b72d-11e8-9c05-c48eb0b37420.png)

**Comment by amcclain** [comment]
@febbraiod heads up in case you had seen these issues when first bringing the control online. If you could help Brendan out as needed and review any fix would be much appreciated.  Thank you!

**Comment by lbwexler** [comment]
Merged in Brendan's fix to the empty text here
https://github.com/exhi/hoist-react/commit/91307ec7f

**Comment by amcclain** [comment]
Double-x resolved with a BP update, font-size fixed in stylesheet and extra weird placeholder text suppressed. ✅
