### ISSUE TITLE
Multiselect behavior on pressing enter is confusing

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#621]
The enter key behaves as if it is a click on the selected item in the suggestion menu. This means if the item is already part of the control's value it is removed and if it is not, it's added. I can see how hitting enter after highlighting a menu item might mean select, but I think it make more sense in the context of a form control for enter to mean 'commit'.

Observed while upgrading BP select to 3.1.X and will try to tackle there, but this is a pre-existing bug so I'm filing in case we I don't get there in that branch.

**Comment by febbraiod** [comment]
Going to wait to discuss. This behavior is documented as intention in the BP docs. Not sure we want to mess with it. However if we did it looked like we get passed the event so we could use that to circumvent this behavior:


onItemSelect | (item: T, event?: SyntheticEvent<HTMLElement>) => voidCallback invoked when an item from the list is selected, typically by clicking or pressing enterkey.
-- | --

**Comment by amcclain** [comment]
I find the current behavior to be pretty natural - I definitely press <enter> without thinking to select/add an item, and the fact that the same key removes the item makes sense.

In the multiselect control I think I am naturally considering the enter and arrow keys to be operating on the pop-up as soon as that's show.  

Honestly I think I expect <space> to also work to toggle a selected item in the same way. It does not - it adds a space to the typed input. I can understand why that's required though if you have options with spaces so **not** proposing we try to change.

**Comment by febbraiod** [comment]
Ok sounds good to me. Closing.
