### ISSUE TITLE
RelativeTimestamp - tooltip + prefix

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#623]
Two small enhancements I would propose for our relative timestamp:

* Add a tooltip to show the full date / time on hover - GitHub provides an example of this on their relative date outputs. A simple span title should be fine, and suggest we use `formatDateTime()`.
* Add a new option to supply a prefix string - text you want to appear to the left of the timestamp. This would let us bundle up the "Last updated" bits that are very common in toolbars, etc. Those labels can then cleanly go away if there is no timestamp that's output, don't require spacing/padding, etc.

**Comment by lbwexler** [comment]
👍
