### ISSUE TITLE
Date picker pop-up month chooser alignment

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#630]
The double arrows here appear to be misaligned / smooshed against the month. True for all months, not just something particular to relatively-long-string "September".

![toolbox](https://user-images.githubusercontent.com/225806/45714592-f22de900-bb46-11e8-9a0f-7618116c1139.png)

**Comment by shravnk** [comment]
[This](https://github.com/palantir/blueprint/blob/478e7a8ca7cf121be011789010d9dcd43dceb5c7/packages/datetime/src/datePickerCaption.tsx#L117) causes the error
