### ISSUE TITLE
Date picker month/year selector combos don't show when in dialog

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#631]
(Observed in client app. Verification required in Toolbox - e.g. by adding a date control to the rest editor example.)

The month/year selectors in the date picker component do not appear when the date picker/input itself is shown in a modal Dialog component. Clicking them appears to do nothing (z-index issue?)

**Comment by febbraiod** [comment]
Could not reproduce as described. I put a dateInput by itself in a dialog that I had set up for another test, and the selector worked fine. Also tried adding a dateInput to our rest controls (there isn't one as of yet). The selectors were still visible but the menus behaved very badly. When clicking on the selector the menu appears, flickers and disappears. Not great, but not this reported bug either.

**Comment by amcclain** [comment]
Closing this based on Don's comment above.  We can let it come back at us if we get more active reports and can more easily reproduce.  We've gone through a few updates on the underlying libraries, so things might well have changed.
