### ISSUE TITLE
Grid: custom/dynamic row class

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#637]
API at GridModel level to set a class on a row based on the row's data.

Exposing some of the underlying ag-Grid options in a managed way: https://www.ag-grid.com/javascript-grid-row-styles/

**Comment by amcclain** [comment]
@TomTirapani will route this to you as I think it would be relatively close to the work in #629

**Comment by TomTirapani** [comment]
This (and #629) addressed in PR: https://github.com/exhi/hoist-react/pull/646
