### ISSUE TITLE
Review `required` vs. `notBlank` validator constraints

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#638]
Do we think there's a real-world use-case for the `required` validator allowing empty string? 

This is somewhat informed by the fact that one or more of our inputs appear to take a `null` value to `""` when tabbing through or setting then manually clearing the value, but in general asking if the distinction is helpful.

GORM has `allowBlank` but that's in contrast with the more explicit `nullable` constraint - not sure if that informed the current setup or not. In our case with the name `required` I think we could be more general but writing up this ticket to discuss. 🤔

**Comment by lbwexler** [comment]
I think you are right w.r.t to emptyString being rejected by 'required'.  

But what about a couple of empty 'spaces'?  Note that notBlank is actually doing a trim() before rejecting.   I guess simplest would be to fail that as well

**Comment by amcclain** [comment]
Yes I think so - can't think of any valid use case for accepting "    ", only possible bug reports 😄 

A user who really didn't want to type something but still wants that form to be valid can go with "xxx"
