### ISSUE TITLE
HoistInput addition: TagInput

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#654]
Hoist wrapper around https://blueprintjs.com/docs/#core/components/tag-input.

Similar to MultiSelect - and perhaps it would be possible to config MultiSelect to support this - but for when you don't have a list of options to suggest but just want to allow the user to enter multiple tags of their own choosing. Probably cleaner to have this be a simple component without any of the select baggage all around.

Interesting question as to how we would want its value to be output - could be a string with a separator - I think that's what BP does - or an array of strings - which might be somewhat nicer.

**Comment by shravnk** [comment]
See #664 and toolbox [demo](https://github.com/exhi/toolbox/tree/tagInputComponent)

**Comment by shravnk** [comment]
This functionality is available via `enableCreate` on the new `Select` component.

**Comment by lbwexler** [comment]
👍
