### ISSUE TITLE
Input component style issues in dark theme

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#657]
It is a slightly different color from the form background, but only barely:

![screen shot 2018-09-21 at 10 30 13 am](https://user-images.githubusercontent.com/225806/45896622-91dab980-bd89-11e8-8f79-e141e2b4b8e1.png)

**Comment by shravnk** [comment]
In the same vein, border on TextArea:
<img width="489" alt="screen shot 2018-09-21 at 1 35 13 pm" src="https://user-images.githubusercontent.com/33368494/45896824-4e8d4480-bda3-11e8-87f2-b76d017b70f0.png">

**Comment by amcclain** [comment]
Thanks for posting - just noticed that and came here to say the same!

**Comment by amcclain** [comment]
Like the first one - both an improvement of course but first one seems like it would be a clearer contrast with the on position.

**Comment by shravnk** [comment]
Ok, agree - the only concern I had about using a box shadow was that it overrides an !important rule in blueprint.css (see lines 2010,2011). Kind of breaking a pattern but I think it makes sense for this case.
