### ISSUE TITLE
Support absolute sorting in grids

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#659]
Certain types of values (e.g. pnl values) are more useful sorted by absolute value. This is a custom feature we added to the Ext toolkit which we should bring to the react toolkit.

Columns should support an `absSort` flag. When enabled, sorting a grid column by clicking on its header would loop through 3 sort states (ascending, descending and absolute descending). Will likely require some UI customisation to display an appropriate sort icon when abs sorted.

**Comment by TomTirapani** [comment]
Implemented using a custom header component, and a custom column comparator.
https://github.com/exhi/hoist-react/pull/662
https://github.com/exhi/toolbox/pull/83

**Comment by lbwexler** [comment]
Fixed in https://github.com/exhi/hoist-react/issues/659
