### ISSUE TITLE
Icon only buttons should be a consistent width

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#661]
I would expect buttons that contain only one of our FontAwesome icons to be a consistent width. This would avoid subtle but noticeable alignment issues, e.g. with stacked toolbars.

![screen shot 2018-09-25 at 11 40 24 am](https://user-images.githubusercontent.com/225806/46035582-388bc680-c0b8-11e8-85cb-81c709c7374f.png)

**Comment by amcclain** [comment]
The download/export icon seems to be the most common example - in Toolbox most icons are 33px wide, but this one is 34.63px

**Comment by shravnk** [comment]
See #666
