### ISSUE TITLE
Grid Store Filter Does not correctly filter tree data

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#668]
If a tree parent has multiple similarly named children, ie:

-parent
---child1
---child2
---child3

typing 'chil' in the filter will remove ONE of these children from the view.  It should not remove any.

**Comment by cnrudd** [comment]
You can see this bug in the treeWithCheckbox branch of toolbox, where I have updated the data sample to have similar names.   Filter for 'goog' to see the bug in the Market Hawk > Equity >  branch.

**Comment by lbwexler** [comment]
This regression actually does not relate to TreeGrid, but to StoreFilterField itself

Its the result of the following commit:
https://github.com/exhi/hoist-react/commit/2c894c3eeb58660f8850de6a4debdce2e3623b78
Please see the following:
https://siderite.blogspot.com/2011/11/careful-when-reusing-javascript-regexp.html

Anselm -- were you seeing performance issues with the Regexp as specified?

**Comment by lbwexler** [comment]
Pretty sure the appropriate change is actually to return the "global" flag.  Don't think it is actually buying us anything here.

**Comment by lbwexler** [comment]
Fixed in https://github.com/exhi/hoist-react/commit/788fa3.  Please let me know if any objections here.
