### ISSUE TITLE
Namespace local storage keys by username

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#674]
With non-SSO apps, we could have multiple users logging into a web application under one OS/machine-level account.  It's a relatively rare edge-case given our standard corporate use-cases, but it is not that far-fetched.

Given that, we should consider mixing the username into the key used to fetch/create localStorage instances - see https://github.com/exhi/hoist-react/blob/f4a205c40473aeab1b0f335e50695ef8652f7e7d/svc/LocalStorageService.js#L58.

It might be good at this same time to swap to appCode (vs name) and maybe do some simple hashing of both appCode and username to provide some light obscurity around who has keys stored under a given account.  Again should stress here that none of this is intended as a security measure - truly sensitive stuff should not be put into local storage at the app level unless we know that the app will only be used on single-user machine logins.

**Comment by TomTirapani** [comment]
PR: https://github.com/exhi/hoist-react/pull/1075
