### ISSUE TITLE
Grid - state management for pinned columns

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#687]
Columns can be pinned / locked to left/right via config.  Once there is a pinned column in place, the user can by default pin other columns by dragging it to the pinned side.  Even without a pre-existing pinned column, a user can pin a col by dragging to the left edge and waiting a bit.

However we are not tracking pinned state for columns, either at GridModel or GridStateModel level. I attempted to add basic support for this, but was tripped up as the ag-provided state we listen for did not seem to include updated pinning status - i.e. a just pinned or unpinned column did not show as such. Perhaps ag-Grid updates this state later in a further operation after fully resolving column order - I didn't have a chance to look.

Even if/when we have that working, we will might need to think carefully about column state and newly configured columns / column order / etc.

For the moment, I think it is safer to force the `lockedPin` ag column property, which tells the grid to disallow any user-driven pinning.  This does not lose current functionality - cols can't be pinned by the user anyway as gridModel sync immediately unpins them - but it does minimize grid default UI that promises to set pin status and then ends up being confusing/misleading when that fails to work.

**Comment by shravnk** [comment]
See [this branch](https://github.com/exhi/hoist-react/tree/pinnedGridCols). Pinned status does not change onDragStop, but rather when user clicks and holds for one second on the far left/right of the grid. The onColumnPinned hook refers to this event. As far as I can tell it's an ag-grid bug that the pinned status is not stored in the columnState, where it could be accessed by other event handlers.
