### ISSUE TITLE
Enhance Copy Support in grid

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#690]
Would like to have a build-in ability to copy a *cell* value only  as well as the entire selection.
This is a facility we had in Hoist-Sencha.

Need to make sure our RecordActions are getting metadata for column/cell to do this.

**Comment by amcclain** [comment]
We could consider generally re-implementing the built-in copy options of the ag-Grid context menu when we do this. Add the menu items ourselves, use our copy icon, have a hook for whatever other control or customization we might want to apply here.

**Comment by lbwexler** [comment]
See the following ticket as well -- as part of this enhancement, need to be sure to handle hidden columns correctly.

https://github.com/exhi/hoist-react/issues/916
