### ISSUE TITLE
Minimal mode for displaying form validation messages

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#692]
Our current approach of showing `FormField` validation messages underneath the field is nice in that it displays any messages directly inline, but has the negative side effect of shifting the form layout vertically as messages come and go. For complex / aligned forms this can be very distracting.

We should support a mode where validation messages are shown in a more minimal way that doesn't disrupt the layout - i.e. an icon that appears next to the label and has the messages in a tooltip. This could be in concert with some additional styling - maybe turn the label color red as well?

* We should ensure any approach works well and looks good across the various input types. (i.e. switch, jsoneditor - not just text/number fields).
* We should avoid making the label jump around if we can as well in label-inline mode. Maybe we need to be more clear about its own L/R alignment relative to the input.
* We can support a prop to switch between the two modes - unless we can get to a place with the more minimal mode where we think it's better all around, in which case let's keep things simpler and just do that.  I'm not sure in advance how that will turn out.

@shravnk - could you take a look here and review options with @TomTirapani ?  He knows the particular client use-case that's driving this right now.  Thanks much.

**Comment by shravnk** [comment]
Ok will do. It seems like our current implementation is redundant - displaying tooltip on hover/focus of the validation message. Will look into adding an icon i.e. "!" and a tooltip onFocus of the form itself.

**Comment by amcclain** [comment]
It's not entirely redundant as there can be multiple validation errors on a single field, or in general a longer message than fits in the inline text.  But still, agree that since we already had to have the tooltip option for those cases, we're not far from putting it on a more minimal icon.
