### ISSUE TITLE
Toolbox->Grids > Tree->'Choose Columns':  'Name' column should be displayed and marked LOCKED for Custom column selection UI

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#696]
Hoist React Toolbox -> Grids -> Grids > Tree -> Click 'gridPanel' icon -> Navigate to 'Choose Columns' 

 'Name' column should be displayed and marked LOCKED for Custom column selection UI

**Comment by amcclain** [comment]
Hi Malvina as discussed can we please aim to keep these titles  as concise as possible and have the steps to find / reproduce in the body of the ticket thanks

**Comment by lbwexler** [comment]
This is a dup of https://github.com/exhi/hoist-react/issues/695.

I renamed that a bit for clarity.

**Comment by mpeckerman** [comment]
Anselm, will do. Ty
