### ISSUE TITLE
FetchService - requestKey / autoCancel functionality

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#698]
Looking to bring forward (with a review to see if it still seems like the best approach) the functionality we had in hoist-sencha [AjaxPromiseService](https://github.com/exhi/hoist-sencha/blob/develop/grails-app/assets/src/xh/all/svc/AjaxPromiseService.js) around tagging requests with a string key and instructing the service to auto-cancel any pending request if a new req. comes in with the same key.

Use case is common pattern where you are navigating through a master/detail grid that loads details async on selection change and you change the selection before a prior detail loads.

The developer working on this ticket may want to look at https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort as a way to implement this on fetch.

**Comment by lbwexler** [comment]
nice find on the AbortController! Looking now

**Comment by lbwexler** [comment]
👍
