### ISSUE TITLE
StoreFilterField needs to be hidden column aware

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#700]
[snippets from slack convo]

do you guys think that StoreFilterField should consult values in hidden columns? Should we consider making it (optionally) grid model aware, so it can only search on visible columns?

colin [12:17 PM]
i think it should be an option : searchHiddenColumns:  false   as default

atm [12:19 PM]
So in that case you would still configure a filter field with a set of (store) fields you wanted it to search, but  then if the gridModel is in the mix and one of those fields is in a hidden column (or not in a column at all?) it would not be used for matching?

atm [12:21 PM]
would it be better to have a dedicated GridFilterField component to not overload StoreFilterField or is that just confusing?

john.haynes [12:21 PM]
would be nice if you could just give it a grid model and have it filter on all visible columns which are associated with a field too
haha

john.haynes [12:22 PM]
yeah GridFilterField sounds like a good idea to me

colin [12:22 PM]
GridFilterField+1

lee [12:22 PM]
I like the idea of less components, and ‘optional props’
so GridFilterField -1

atm [12:23 PM]
I’m thinking of our storeContextMenu where it has an optional relationship with a gridModel that I’ve found tripped me (and others) up a few times
You don’t need to supply it - but you probably do for much of its functioanlity
I guess it also depends on how deep we go into the grid integration.  To have it auto-introspect the columns, understand how they might be renndered and what is “searchable”, know about grouping where a col is hidden but not really, etc.

**Comment by lbwexler** [comment]
I have a solution for this I think

**Comment by amcclain** [comment]
Fixed in #715
