### ISSUE TITLE
Default 'Copy' on ContextMenu on DataView is bust

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#704]
The Copy Item appears to just copy out an '[Object] object'  string.

See Toolbox 'News' example and 'DataView' example in grids

**Comment by lbwexler** [comment]
Yes -- absolutely.  Brendan -- can you whack the default context menu here on DataViewModel?  Think it probably was just a copy error from the very original version.

**Comment by shravnk** [comment]
Sure thing
