### ISSUE TITLE
QueryComboBox options are not guaranteed to be the most-recently requested

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#710]
The QueryComboBox does not protect against out-of-order promise resolution on `queryFn` callback calls, causing a mismatch between the current "value" and options. Especially noticeable with slow lookup endpoints.

**Comment by lbwexler** [comment]
Assuming the queryFn you are using is actually using a fetch underneath this should be easy to mitigate by providing an 'autoAbortKey' call to the fetch.

**Comment by amcclain** [comment]
Can retest with completely rewritten selects in #663. Using react-select now which has actual support built-in for async.  My hunch would be that the comp handles internally but should check if not can add autoxcel to async implementation within new select to do so

**Comment by haynesjm42** [comment]
Will do, thanks

**Comment by amcclain** [comment]
Hi - I had a chance to give this a test and I think we are good.  I forced a longer delay with a particular string in the Toolbox example, and was able to type past it while waiting, get a narrower set of results, then confirm the delayed promise returned via a console.log but didn't add its results to the combo options.  Closing but of course please re-open or give a shout if further issues arise.

**Comment by haynesjm42** [comment]
Thanks for testing, confirmed this is fixed in the client-app where I originally saw the issue as well.
