### ISSUE TITLE
Rename Column.hide -> hidden

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#716]
More familiar/natural to my ears, and more consistent with other hidden configs in the toolkit. Will now differ from direct ag-grid API, but that's the business we are in.

Need to consider potential saved state to see how that would be handled.

**Comment by lbwexler** [comment]
Let's fix this now, while several column-hiding client apps are still in pre-deployment.

**Comment by lbwexler** [comment]
Reaching out to John Haynes re: whether we need to do anything special to support state for grids in the Risk projects.
