### ISSUE TITLE
NumberInput should wait until blur to convert from 2m to 2,000,000

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#730]
The NumberInput field allows typing number like 2m when enableShorthandUnits=true.
But it changes the value displayed in the field immediately after the 'm' is typed to 2,000,000.
This behaviour should be changed so that the switch to 2,000,000 happens on blur.

**Comment by amcclain** [comment]
@febbraiod @lbwexler I know this was something you guys went back and forth on. 
Can make an argument both ways I think - it's definitely surprising how it is now but believe implementation-wise there were reasons why this started happening.

Any changes should be considered post #663 merge

**Comment by lbwexler** [comment]
I discussed this with cnrudd, and asked him to file.  I think we made the behavior demonstrably worse, largely in the service of simplifying the code -- I don't think there were any compelling reasons or bugs with the other way of doing it, and I take responsibility for the change.

Yes, we will wait post #663 for any changes here!

**Comment by amcclain** [comment]
Cool thanks - I do agree it's surprising and a bit disorienting when the format changes so suddenly. Would be great to strike a better balance here. Wasn't sure how tricky that would be - but we can do it I am sure!

**Comment by lbwexler** [comment]
Don -- Can you take a look at this one?  Ran into it yesterday when trying to enter in a number in scientific format.  Now think the current behavior is just deeply wrong

**Comment by febbraiod** [comment]
Starting this now, sorry to have missed it.

**Comment by febbraiod** [comment]
Parsing on blur is working, however we also need to parse if the user hits the enter key (Enter == commit == parse). Speaking to Lee there is also some concern that this would be broken if used with 'commitOnChange' as the committed value of '2m' would literally be the string '2m' until blurred. Lee thought that possibly with commitOnChange we do want to do the parsing immediately, but that would leave it in the 'broken' state we have now. 

I think if you are using commit on change you are getting exactly what you asked for (2m), and that the combo of 'enableShorthand' units and commitOnChange is ill advised and can be looked at from a 'Buyer beware' perspective.

**Comment by lbwexler** [comment]
Thanks for diving back in Don -- yes to the approach in the last sentence.  That is going to be the ticket.

**Comment by nadkarniarjun** [comment]
➤ Don commented:

Note for Arjun here: This issue was just closed on github, however I'm still seeing it as open here. (Even though it says: ┆Task is synchronized with this GitHub issue: https://github.com/exhi/hoist-react/issues/730)

**Comment by nadkarniarjun** [comment]
➤ Don commented:

Disregard. I'm guessing it just took a minute to sync up.
