### ISSUE TITLE
fetchService needs a 'delete' convenience method

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#731]
fetchService has getJson, putJson, and postJson.  
Developers have asked "Where is deleteJson?"

See https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7  for what kind of status codes should be accepted from servers responding to a DELETE request.

**Comment by amcclain** [comment]
Thanks for filing (I had promised to do as much but didn't).

Thinking about this again - the name would be a bit weird. Is it implying that you are sending JSON in an encoded body, as post/putJson do?  Or just that it will send whatever opts you have specified, without any additional encoding, but set the DELETE method and decode a JSON response?

I was assuming the latter, but again the name just doesn't sound right. You're not really deleting JSON - you're issuing a DELETE command that maybe-accepts-and-does-expect a JSON return.

Does my concern make sense?  I'm wondering if we really want this method. The point of the predefined helper methods is to add a bit more clarity around certain structured kinds of requests, and there might not be an "obvious" way this one should work.

**Comment by cnrudd** [comment]
Yes, I agree it could be confusing.   If it were called deleteJson, I would say the rules would have to be:

1. you may or may not send along a body, but if you do, it must be a JSON body.
2. you may or may not reply with a body, but if you do, it must be a JSON body.
3. the METHOD used will be DELETE

Seems easy enough to document and follow, if we decide to implement it.
