### ISSUE TITLE
Checkbox and Switch should bind to boolean values only

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#734]
Right now there is a workaround in Checkbox and Select to allow it to bind to a model field that might have a string value.  This would not work for a 'value' set by a prop, which is type checked to be a boolean.

This is a workaround that is currently needed to support the Preference and Config editing in the Admin client, which store boolean values as strings, and pass them to RestEditor We would like to modify those uses to modify their source data to present booleans to the control.

**Comment by lbwexler** [comment]
Brendan - let me know if you want to discuss after you have had a look

**Comment by shravnk** [comment]
I think I've got it, thank you

**Comment by shravnk** [comment]
See #771

**Comment by lbwexler** [comment]
Fixed.
