### ISSUE TITLE
App load timing inaccurate when not already authenticated

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#735]
Time spent sitting on a login prompt will be included in the load time, which is clearly silly (although also not an issue for our primary target, SSO apps).

For non-SSO apps, we could:
* Not track load times for non-auth'd users - set a private flag on XH if we go to `LOGIN_REQUIRED` that disables the later track statement.
* Track load when we go to `LOGIN_REQUIRED` - won't include service init, which is misleading.
* Do the bookkeeping with another timestamp installed when login prompt shown and then subtracted out when init resumes...  

I think I favor the first option.

**Comment by lbwexler** [comment]
Fixed in https://github.com/exhi/hoist-react/pull/762

Was as easy to do the second option using observables.  Refactor will also allow more detailed analysis of other aspects of loading, and also breaks out the tracking nicely into a single method.
