### ISSUE TITLE
Store/GridModel slow to *reload* large Datasets

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#736]
Seen on a client app -- *Reloading* 50,000 records into the store of a GridModel,  can get strangely 
slow.  

But clearing the data first, then wait(0) before loading into an empty store fixes the problem !?

Not obvious if this is the Store, the GridModel, or the Grid, or the AGGrid.....  but something to do with reconciling the two states is very slow

**Comment by amcclain** [comment]
Would be curious if you saw an immediate difference here if we commented out the force refresh:

https://github.com/exhi/hoist-react/blob/110a17d09a9a6f2ca57d276edd0eea9d05c75ac3/cmp/grid/Grid.js#L303

Obviously not a solution, but would be a data point.

**Comment by amcclain** [comment]
Also wonder if we could be getting an anti-optimization out of our use of `deltaRowDataMode`, in the cases where we are reloading data with all new object references. Could we be taking a hit from the grid attempting to do an incremental update by comparing row node IDs, finding they match in almost all cases, then doing the object comparisons and finding that they have in fact changed and having to tear it all down anyway...  (Re-reading [this section](https://www.ag-grid.com/javascript-grid-data-update/#delta-row-data) of their docs.)

Apologies in advance if these comments are a series of red herrings...

**Comment by lbwexler** [comment]
I am closing this.  This problem has gone away with our latest upgrade to ag-Grid and refactor of grid columns. 

We have a different issue with treeMode:true being slower to load, but that really seems like a seperate  issue.
