### ISSUE TITLE
Grid emptyFlex column creates gap if horizontal scrolling active

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#740]
Noticed this in a client app grid with a number of standard-width columns + an emptyFlex at the end. It can be replicated e.g. in the Admin Client > Caches grid.

If overall width is such that horizontal scrolling is required, the emptyFlex appears to create a gap between the last real column and the vertical scroller:

![screen shot 2018-10-24 at 10 10 55 am](https://user-images.githubusercontent.com/225806/47448570-33806c80-d775-11e8-9e92-de8dc00a8479.png)

But if the grid is expanded to be wide enough to not horizontally scroll emptyFlex renders as desired:

![screen shot 2018-10-24 at 10 11 00 am](https://user-images.githubusercontent.com/225806/47448577-38452080-d775-11e8-934e-0d357a216a88.png)

**Comment by lbwexler** [comment]
This is a small nit.  Discussed with ATM.  Not a priority.
