### ISSUE TITLE
Expose Grid ExportManager as a service

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#759]
Most if not all of the code within the current `grid/impl/ExportManager` class could be exposed as a `DataExportService`. 

This would have the advantage of using the service pattern for this kind of transform/post/fetch data task, and could also allow us to work on a more general API to POST data from sources other than a grid model to the server-side endpoints for Excel spreadsheet generation.

We currently have one client app that's assembling this data package manually at the moment, duplicating some of the logic within the impl class. It's a powerful feature to be able to further leverage our server-side export code to generate Excel sheets in a standard way, and we want to expose it consistently and with a maintainable API.

**Comment by lbwexler** [comment]
Hi:  Just want to say that I definitely agree with this.  I wonder whether it might be more pragmatic  to create a 'GridExportService' that is GridModel aware, rather than trying to abstract into the more general DataExportService.  Its all pretty grid specific, and could be made to work for DataViews as well, but don't know that it needs to be more general than that.

**Comment by amcclain** [comment]
We have this one use case (which could continue to be handled as a one-off) where we have a set of data that doesn't need to be / is not shown in a grid at all but is fetched on demand by the client for the express purpose of re-exporting it out to Excel through the Grails layer.  (I.e. the available input is a JSON API and the desired output is an Excel table).

Just occurred to me though....I don't think there's any reason why we couldn't construct a "headless" GridModel - i.e. just the model no grid component - and use the standard code paths from there.  Looking quickly at the existing GridModel and ExportManager classes, I don't *think* they depend on reading metadata or making API calls from an instantiated ag-grid.  We could give it a try.

Again, not to let this one (rather unusual) use-case drive the discussion here. Main goal is to have a service vs. the somewhat-ambiguous kind-of-class that is ExportManager.

**Comment by lbwexler** [comment]
Think this is a great idea.

**Comment by TomTirapani** [comment]
This issue has been folding into the related issue #701 in the following PR:
https://github.com/exhi/hoist-react/pull/764
