### ISSUE TITLE
PrefService.set() issues with Object/Array prefs

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#765]
PrefService.set() is updating the cached data with the value passed to it, which could be an Object or Array, and could be the same reference which the App is holding onto. If the App modifies the Object properties or Array contents without cloning, then it is also modifying PrefService's cached copy of the value, and calls to PrefService.set() will never pass the `isEqual` check and thus never be updated on the server. This could also cause some interesting bugs with the deferred push to the server after a set, where the value persisted is different from what was passed to PrefService.set() since the App could have modified the value which the PrefService updates map is holding a reference to after calling set().

To be consistent with PrefService.get(), PrefService.set() should clone the value before updating the internal cache, and also pass a clone of the value to the `prefChange` event so Apps can be guaranteed to always be given a copy of the pref value.

**Comment by lbwexler** [comment]
We went with an alternative approach to freeze the values returned by the service, and put the onus on the client to make clones if neccessary.  Closing.
