### ISSUE TITLE
Investigate how to support the Edge browser in hoist-react

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#781]
the Edge browser does not support promise.finally, which hoist-react uses.
Once we have found a polyfill for promise.finally, see if Edge fails on anything else.

**Comment by amcclain** [comment]
👍 Thanks for filing this - agreed that we should support Edge unless something really goes wrong.

I'm not clear on how the polyfill stuff interacts with Babel and the presets/plugins we are specifying within our standardized webpack config - 

https://github.com/exhi/hoist-dev-utils/blob/59227acddb11258dd0b17fa05b1f7218d7dfeff2/configureWebpack.js#L210

This might be the place where such support is added via babel-polyfill or similar.  It seems like this particular issue (Promise.finally in Edge) has a good amount of chatter on the internet.  What a pain - I thought Edge was supposed to leave this all behind!

**Comment by cnrudd** [comment]
I investigated this on a Windows 10 guest w/ Edge 17 running in Virtual Box on my 4 core MBP.
I gave 2 cores to the Windows 10 guest.

Our current configureWebpack.js gives the Edge browser support for Promise.finally .
This is confirmed by changing this line:
https://github.com/exhi/hoist-react/blob/2e156b995b8ddf33a9031b245035336f17875dc5/static/index.html#L22
to 
`if (false) {`

to allow Edge to load our app.  (The promise.finally is polyfilled by our js after our blocker tests)
and then typing Promise.finally in and Edge console for toolbox to see that is defined as a function.
(An Edge console loaded for another site, like https://www.google.com/?gws_rd=ssl, shows Promise.finally as undefined)

And also our Toolbox app can now load pages in Edge that run this 'finally' code:
https://github.com/exhi/hoist-react/blob/2e156b995b8ddf33a9031b245035336f17875dc5/desktop/cmp/tab/pane/Tab.js#L79

like /app/charts/olhc .

Toolbox's Grids test page is failing.   I still need to find the cause of this.  No JS errors are thrown in Edge despite the failure to render a grid.

**Comment by cnrudd** [comment]
In the Edge v17 that I am using, it looks like Edge is choking when it is asked to Mobx observe.ref agApi.
I chokes/hangs on this line:
https://github.com/exhi/hoist-react/blob/1e91c1d581eca17ad2c8118a825a62b08f068030/cmp/grid/GridModel.js#L240

The agApi is a big object for sure, but AG Grid's demo page does work in Edge: https://www.ag-grid.com/example.php  
They are not tracking agApi with mobx though.

**Comment by cnrudd** [comment]
I wonder if maybe, rather than make the gridModel.agApi observable, we instead just make a flag that it is ready observable, and then assign the agApi to the gridModel.agApi property (not observable) if that would help?

**Comment by cnrudd** [comment]
Above hunch was right.
hoist-react branch MS_EDGE_SUPPORT allows toolbox to be run in MS Edge on windows 10.

As to why... haven't looked into that yet:  
is mobx observable.ref not implemented as believed?
or does Edge not handle object assignment by reference correctly?

Curious to see if this fix would also fix the new mobx/agApi error I see in our popover that contains a grid components in the client app I am working on.

Mobx says observable.ref can be used for observing 3rd party Apis, but I think that is a risky thing to do.

**Comment by cnrudd** [comment]
I looked more into how mobx works.   And couldn't find any reason to support the idea that Mobx does not work correctly on @observable.ref

I went back to retry the develop branch in EDGE and today it works fine.

So, I am coming to the conclusion that EDGE can be buggy.  But our current code supports it.

Here are two PRs that update minor things to allow EDGE support:
https://github.com/exhi/hoist-react/pull/806  Removes the Edge lockout, improves the IE 11 lockout
https://github.com/exhi/toolbox/pull/112  Fixes tree grid checkbox styling for Edge.


These are some of the mobx code and doc pieces I looked at when looking into observable.ref
https://mobx.js.org/refguide/boxed.html
https://github.com/mobxjs/mobx/blob/f944b5413f2f4b9de89e00e7de1ddde2a178e19d/src/types/modifiers.ts#L42
https://github.com/mobxjs/mobx/blob/e099329e5d1246632b05601d79220295af3a03cb/src/api/observable.ts#L96
https://github.com/mobxjs/mobx/blob/e099329e5d1246632b05601d79220295af3a03cb/src/api/observable.ts#L105

**Comment by cnrudd** [comment]
Maybe the "Miracle on Edge" bugfix that happened between the time I first tested 13 days ago and yesterday is not attributable to just "Edge is buggy"  but to the update in the concerned libs that we are using in v16.0.0-rc4:
https://github.com/exhi/hoist-react/compare/9173f3aab71c6cce10ec15b5c1765bbfe6538999...v16.0.0-rc4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

    "ag-grid": "~18.1.2",	    "ag-grid-community": "~19.1.2",
    "ag-grid-enterprise": "~18.1.1",	    "ag-grid-enterprise": "~19.1.2",
    "ag-grid-react": "~18.1.0",	    "ag-grid-react": "~19.1.2",

and 

    "mobx": "~5.5.2",	    "mobx": "~5.6.0",

**Comment by lbwexler** [comment]
that would make more sense, yes.  Good example of how taking upgrades can help you in ways you don't even realize....(as well as hurt you in ways that you immediately do realize)
