### ISSUE TITLE
Match Select placeholder color to standard input placeholder

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#782]
Select component draws its own custom placeholder element, which appears to have slightly different styling (more opaque/darker) than the built-in textinput placeholders.  

Not a crisis, but is noticeable on forms where you have a few of them side by side.

I wonder if there is a way to get exactly what style is used for placeholders by the browser (or at least, by Chrome).

**Comment by lbwexler** [comment]
Giving this to Tom and Brendan, as they are working on the related select styling ticket: 
 
https://github.com/exhi/hoist-react/issues/836
