### ISSUE TITLE
Grid support for Pivoting

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#783]
Need to be able to handle Pivot grid configuration for a client app. 

https://www.ag-grid.com/javascript-grid-pivoting/

Requirements:
* Hoist Grid/GridModel able to handle Pivot mode for ag-grid
* Able to use ag-grid Tool Panel and Row Group Panel for configuring the grid
* Grid state (columns, sorting, grouping, pivot) able to be saved and restored easily
* Grid features work (if applicable) when in Pivot mode (selection, context menu, etc.)

**Comment by lbwexler** [comment]
Closing.  We took an alternative path of Creating AgGridModel for this type of application.
