### ISSUE TITLE
Investigate Performance Issue with RecordAction column

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#784]
We have seen in a client app that RecordAction column can really slow down scrolling.  There may be ag-Grid <=> react optimizations we are not taking advantage of that we could be.

**Comment by lbwexler** [comment]
It seems clear that the multiple React components are really dragging this column down -- and as far as I can tell, we really don't need to be doing this with react.

Can we look at an Html implementation of this?  We already seperated this from the non-column form of it, so we should be nicely set up for that.

**Comment by haynesjm42** [comment]
Looking at this now
