### ISSUE TITLE
DimensionChooser - doc updates

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#788]
A few quick TODOs around initial dimChooser integration.

- [x] Add PropTypes w/standard doc comments to the component. 
- [x] Remove use of defaultProps - don't think we have these left in many places.
- [x] Toolbox example - it's in the example app, but I think it should be in TreeGrid tab and be called out in the descriptive header.

**Comment by shravnk** [comment]
Think we're good here

**Comment by lbwexler** [comment]
👍 

Thanks for helping us wrangle this ticket count down!
