### ISSUE TITLE
Accept 'config' as Model prop for certain objects 

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-react#797]
For convenience would be nice to accept a config object for the `sizingModel` on Panels instead of requiring an instance of PanelSizingModel, which I should only really need to construct ahead of time if I want to control the panel state externally, which is rare.

Want to be able to write code like this:
```
panel({
    title: 'My Panel',
    sizingModel: {
        side: 'left',
        defaultSize: '300'
    }
)}
````

**Comment by lbwexler** [comment]
John and I discussed this extensively today, and would like to expand the scope of this in two ways:

1) We think it makes sense to rename "PanelSizingModel" to "PanelModel", and have it be the core model for a panel.  We doubt that Panel will get additional model like functionality beyond sizing, but if it does we can hang it here.  This also brings the API of this core object inline with the rest of the API.

2) We would like to allow Panel, TabContainer, and perhaps GridModel to all take a config object as their 'model' prop to allow anonymous creation of a local model.  This will be very useful in the common case where the application does not actually need a programmatic reference to the model, and just wants to specify some properties on it (e.g. preferenceName).  We could eventually extend this behavior to HoistComponent generally.  One question is whether we would call this prop 'model' or 'localModel'.  

Although these are somewhat orthogonal changes, think it makes sense to do them both together, as apps can simply adjust the Majority of PanelSizingModel declarations to inline configurations in one change.

**Comment by lbwexler** [comment]
Fixed in: 
https://github.com/exhi/hoist-react/commit/bc43dc53e5caf
