### ISSUE TITLE
Possible 'afterCommit' handler on HoistInput

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#803]
In a client app we had the need to control the position of the cursor in a particular input if a particular input condition was met. Was only able to accomplish after setting a timeout within the function I passed to our onCommit prop to allow the internal value to be set before attempting to control the cursor.

**Comment by lbwexler** [comment]
Think this is a pretty unusual case, and I think you have found a good workaround.  Would like to avoid complicating the  API/semantics of these HoistInputs any more, if possible.
