### ISSUE TITLE
Port TreeMap components to Hoist-React

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#808]

**Comment by TomTirapani** [comment]
Been thinking about this, and came up with the following discussion points:

## Charting Library

Our existing implementation in PIQ uses `Ext.d3`, and our client apps implementations use Javascript InfoVis Toolkit (JIT). An important decision would be to whether we continue using HighCharts, switch to using D3, or use an alternative library. InfoVis seems quite limited and closely bound to the Sencha framework, so I think that's a non-starter. 

As I see it, each option has the following points:

HighCharts
+ Includes a TreeMap implementation that supports levels - https://www.highcharts.com/docs/chart-and-series-types/treemap
+ The HighCharts library is already bundled as part of hoist-react
+ Our existing Chart component already uses HighCharts, allowing us to leverage existing patterns / light & dark themes, etc
+ May not be as customisable as we would like

D3:
+ Allows us a higher degree of control over the output. This comes at the cost of higher complexity / longer development time.
+ Without the Ext wrapper we were using in PIQ, would have to spend some time reinventing the wheel.

Alternatives:
+ Unfortunately, there don't seem to be many options out there that come with a bundled TreeMap. One candidate that looks quite good is react-vis - https://github.com/uber/react-vis. Is regularly updated, has a good team behind it (Uber), and fits our requirements. But do we want to bring in another library?

I expect our best choice would be to use HighCharts. unless we encounter limitations, in which case we could consider react-vis. Of course, eager to hear any suggestions for alternative libraries we could use.

## API

We can start with a TreeMap and TreeMapModel (for rendering a single TreeMap) with an API that closely follows our existing Chart and ChartModel. Similar to ChartModel, this would support props for HighCharts `config` and setting observable `data`. A large portion of the HighCharts config will likely be defaulted in the TreeMap component, following the convention laid out in Chart.

We can also support the following TreeMap specific props:

+ `color`. Either a single color, or an object of the form `{min: color, max: color}`.
+ `heatField`. Record field to use to determine square color if a min / max color provided. We have existing logic in PIQ to normalise this between 0-1, which we can use to select a color in the range (As a bonus, HighCharts can do this for if we pass the value as `colorValue`)
+ `labelField`. Record field to use to label the squares
+ `algorithm`. Layout algorithm to use. If we use HighCharts, could default to `SQUARIFIED`

## Plan & Structure

1. The first phase would be to implement a TreeMap & TreeMapModel as specified above, that simply accepts a data collection and renders it.

2. The second phase would be to enable the TreeMap to work with an optional `GridModel` (ideally, would still retain the ability to render a TreeMap using pure data from another source):
	+ Use the observable data in the GridModel's store to update the TreeMapModel data, plucking out the `heatField` and `labelField` as required.
	+ Use the Grid's `expandState` to determine which levels of the data we render in the TreeMap, so that expanding a node in the tree expands it in TreeMap. Add a corresponding double click handler to the TreeMap which toggles the corresponding node in the grid.
	+ Use the GridModels selection state to highlight (via a CSS class) selected squares in the TreeMap. Add a corresponding single click handler to the TreeMap which manipulates the Grid's selection
3. The final phase would be to add a `SplitTreeMap` component. This renders two TreeMaps (again, using a GridModel). We have existing code in PIQ which can size the two maps according to the sizes of their contents.
	+ `orientation`. `vertical` or `horizontal`. Determines whether to use a `vframe` or `hframe` internally.
	+ `heatThreshold`. Determines which of the two maps a record would go into. Default `0` for the common use case of pnl values.
	+ `colors`. An array of color props to be passed to each of the TreeMaps. Default would be green and red for positive / negative pnl values.

**Comment by lbwexler** [comment]
Great summary here Tom!

**Comment by amcclain** [comment]
I’m all for the Highcharts approach (so much that I had convinced myself that’s what we had already done in hoist-sencha...).

I think that the split map is really an essential part of our component - it's an interesting question if we would have many applications for a single map without the split notion built in. Of course I can see how componentizing a single map seems like the natural step towards building the split version, but I would want to think it through before adding e.g. gridModel level binding to a single map.

I also remain in favor of the more complex solution that supports hierarchical data, including node expand/collapse, within a single map.  I feel like that's one of the main advantages of the visualization overall.  It could be something that's configurable - perhaps certain maps should only show the top level - but in many cases we have a pretty trivial number of top-level groups that produce an "uninteresting" map, and it's only when you expand to another level of detail that the richness of the visualization becomes apparent.

In the hoist-sencha implementation, when you expand e.g. an overall positive parent node that contains positive + negative children, we create relatively-sized parent nodes in both maps and allocate the children between them.  This admittedly does have the perhaps surprising effect where expanding a node in the positive map changes the viz and internal sizing of both maps, but I think that simply reflects the reality of the dataset. And I don't think there's any other option other than not allowing in-place drilldowns.

Would also like to discuss / think through baking in GridModel to the API.  Of course understand why we would do so to sync the data, expand state, and selection state, and do so easily with a paired map/grid combo.  But the tree component could also be passed the `Store` + `StoreSelectionModel` which should provide the observable data without overly conflating the grid and map packages.

**Comment by TomTirapani** [comment]
WIP PRs here:
https://github.com/exhi/hoist-react/pull/1280
https://github.com/exhi/toolbox/pull/231

**Comment by lbwexler** [comment]
👍
