### ISSUE TITLE
StoreFilterField not working as expected within Toolbox > News example

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#816]
1. Navigate to Hoist React Toolbox -> 'Examples > News' -> 'News Feed' panel
2. Activate 'Quick filter' field
3. Type relevant text / name into the 'Quick filter' field and click Enter / Return button
4.  No data is being retrieved / pulled from the news feed 

Tested with all available feeds

![image](https://user-images.githubusercontent.com/40367298/49043607-952f5e80-f199-11e8-99b8-4c0ed3950626.png)

**Comment by amcclain** [comment]
@shravnk would you be able to take a look at this today to triage? I can confirm that something is behaving badly here. 

I checked another usage of StoreFilterField in the deployed admin app on toolbox-dev and didn't see any immediate issues in that usage. Assuming this might relate to the use of the filter callback in the News example.

**Comment by shravnk** [comment]
On it

**Comment by lbwexler** [comment]
Closing this -- Thanks for chasing down Brendan -- I amended your fix slightly.

**Comment by lbwexler** [comment]
See https://github.com/exhi/toolbox/commit/5ee05d284

(intercepting a committed value and recommitting a bit of a hairy thing -- if you get it wrong, you end up in a loop!)
