### ISSUE TITLE
Date formats produce unexpected output when input is undefined

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#824]
Steps to recreate:

1. Navigate to Hoist React Toolbox -> 'Formats > 'Date Format' Panel -> 'Format tile -> As per design 'fmtDate' function selected 
2. 'Result' tile -> 'Output' -> corresponding to an 'undefined' is populated with Today's date 'YYYY-MM-DD' 
3. Select 'fmtCompactDate' 
4. 'Result' tile -> 'Output' -> corresponding to an 'undefined' is populated with current time 'HH:MMpm (am)' 
5. Select 'fmtDateTime' 
6. 'Result' tile -> 'Output' -> corresponding to an 'undefined' is populated with current date and time ''YYYY-MM-DD HH:MMpm(am)
7.  Select 'fmtTime' 
8. 'Result' tile -> 'Output' -> corresponding to an 'undefined' is populated with current time 'HH:MMpm (am)' 
9. 'Try it' field is populated with date/time 'YYYY-MM-DD HH:MM', where 'HH:MM' in depicted in the military time / 24 hour format

**Comment by lbwexler** [comment]
CR: Don
