### ISSUE TITLE
NumberInput requires two presses of "-" if non-empty

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#825]
A funny edge case, but reported by a client and you can see how it would be annoying if you were frequently editing values. Can replicate in Toolbox, but does not appear to effect raw Blueprint component.

* Enter a value into a number input
* Tab out, then tab back in again - existing value should be selected via default
* Type "-" as if you wish to enter a negative number - input clears, but is now empty instead of containing "-". 
* Type "-" again - works OK and you can continue to enter your negative number.
* Typing a number (instead of "-") works as you would wish, clearing the existing content and replacing it with the just-typed number.

**Comment by lbwexler** [comment]
This just significantly raises the priority of fixing #730 , in my mind.

The need to allow entry of numbers that aren't fully numbers on every keystroke is really the genesis of the entire design of having a seperate "commit" phase and an internal vs. external value.
