### ISSUE TITLE
Display primary datasource connection info in Admin > About

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#829]
It would be useful to be able to quickly check the database (and maybe DB user, if possible?) wired up to GORM from the Admin > About page.

**Comment by cnrudd** [comment]
Developent is done.
See PRs:
https://github.com/exhi/hoist-react/pull/877
https://github.com/exhi/hoist-core/pull/67

**Comment by lbwexler** [comment]
Go Panda!
