### ISSUE TITLE
FieldSupport should allow for the dynamic addition or removal of fields

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#830]
This system seems to be built around a set of fields that are decorated as properties of a model and initilized once. From the initField doc string:
* Initialize this mixin.  Will set all fields to their initial values to be used as the
         * baseline for dirty state and to support `resetFields()`.
         * This method must be called once, before accessing the public APIs in this mixin.

Additionally, it appears underlying fields models sets its fields to an internal '_fields' variable and uses that for all its business.

Had a need for dynamic field sets in a client app and worked around by building subforms and adding those to the parent form dynamically which allowed me to declare each new field as a property on its own submodel. Spoke to Lee who thought that there might be (or at least should be) a addField/removeField public API for this, but unless I'm missing something I didn't see that.

**Comment by amcclain** [comment]
Closing as I have opened #857 to cover the larger refactor that will bring this support in - thanks for raising and pushing the need for this larger refactor into the spotlight!
