### ISSUE TITLE
Select - render selected option with a checkmark in dropdown

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#836]
Right now the *focus* style of our Select component is much more accented than the *selected* style.
This to me seems to be exactly the opposite of what we want. 

The net result, is that it is very easy to get confused, and think that the focused item is currently selected.  

This is especially a problem if you use the Select box for just two items (which we do sometimes.)  The focused item simply looks like the selected item.  You end up thinking that there is nothing for you to change, and wondering why you went in to the select box in the first place!

**Comment by shravnk** [comment]
I had noticed this as well... played around with CSS vars a little and came up with the following:

https://github.com/exhi/hoist-react/tree/selectMenuStyling

**Comment by lbwexler** [comment]
Let's just ensure that what we are doing is standard here.  Worth looking at how other toolkits and os controls handle this.

**Comment by amcclain** [comment]
I hadn't really paid attention to this before, but seeing now that MacOS uses a checkmark in a left-hand gutter to indicate the currently selected option.  That now seems like an obvious idea and one that makes for maximum clarity.  
<img width="670" alt="screen shot 2018-12-14 at 12 48 24 am" src="https://user-images.githubusercontent.com/225806/49985909-b6cf6a80-ff3b-11e8-9350-deb6d9c3e949.png">
<img width="747" alt="screen shot 2018-12-14 at 12 52 16 am" src="https://user-images.githubusercontent.com/225806/49985825-5e986880-ff3b-11e8-82df-49263c60a366.png">

I think the native browser select inputs must be getting this same behavior, as I see it consistently on some web pages loading what look like basic / native controls. Interestingly Gmail seems to provide an example of a custom implementation of the same:
<img width="381" alt="screen shot 2018-12-14 at 12 52 47 am" src="https://user-images.githubusercontent.com/225806/49985899-acad6c00-ff3b-11e8-8325-776f76d3b44d.png">

I think we should look at how difficult this would be to implement with react-select. (I would not be surprised if it's been tried or discussed in the wild.)
