### ISSUE TITLE
ExceptionDialogModel should allow simultaneous display of multiple exceptions.

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#845]
There is a comment in the code to this effect, and we have a model in our "Message" handling that suggests exactly how to do it.

**Comment by amcclain** [comment]
Upon further reflection, I'm thinking we can close these future tickets (leaving them tagged). That way when we get super bored with nothing to do, we can look at closed+future tix and re-open ones that now seem ripe for development.

Hope that sounds reasonable?
