### ISSUE TITLE
Fix Resize Bug in Chart Component

### ISSUE THREAD

**Issue by nadkarniarjun** [exhi/hoist-react#852]
As can be seen on this page in toolbox: https://toolbox-dev.xh.io/app/examples/portfolio

charts will shrink if their container shrinks, but will not expand when their container expands.

**Comment by lbwexler** [comment]
did colin open this?

**Comment by cnrudd** [comment]
Yes, I did.

**Comment by cnrudd** [comment]
Libs I considered:

https://www.npmjs.com/package/react-resize-aware - uses object with onResize Listener
https://www.npmjs.com/package/react-resize-listener  - uses iframe with onResize listener
https://www.npmjs.com/package/react-resize-observer - uses some kind of scrollbar potential detection

Then there are a number of libs that use this:
https://github.com/que-etc/resize-observer-polyfill

https://caniuse.com/#feat=resizeobserver  we would would have native chrome support with a lib that uses -uses resize-observer-polyfill

https://www.npmjs.com/package/react-resize-detector -uses resize-observer-polyfill
https://www.npmjs.com/package/reactjs-resize-observer -uses resize-observer-polyfill
https://www.npmjs.com/package/@zeecoder/react-resize-observer -uses resize-observer-polyfill
https://www.npmjs.com/package/react-with-dimensions -uses resize-observer-polyfill  and uses decorators!  Going to try this one!

**Comment by cnrudd** [comment]
more discussion of resizeObserver: https://developers.google.com/web/updates/2016/10/resizeobserver
