### ISSUE TITLE
Admin grids - misc cleanup

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#863]
Some minor annoyances in the admin client. Nothing critical but worth cleaning up, as the admin client provides a natural reference point for our best practices.

- [ ] Configs - config "Group" col visible, despite being group by
- [ ] Services - same with "provider" column, has random unnecessary refresh icon in toolbar
- [ ] Users - add export button to right of quick filter
- [ ] Client errors - last error column weirdly shows opening `{` only (indicating to me JSON is pretty-printed) on first load, but swapping to another tab and back again shows the full string. Hardly fatal, but what's going on here?
- [ ] Feedback - should be sorted by date for consistency (it might come back that way from server, but grid is not doing a sort as it is for the others)
- [ ] Prefs + User Prefs - group col visible
- [ ] Are the grids consistently masking? On a slow connection I can see a decent lag to load data but no sign of a mask. This includes RestGrids.

**Comment by shravnk** [comment]
Have completed these locally except for the last point. We were not using masks for most of the admin panels. Additionally, I think RestGrid requires a `mask` prop in order to link to wrapping component's `PendingTaskModel`. 

I've already tested that change locally, so let me know and I can just include the change to `Rest Grid` in this ticket's PR.

**Comment by amcclain** [comment]
Please push what you have and open a pull request. Great to get this in.

I think we should handle RestGrid masking in a separate issue - seems to me that it should come with a mask by default but we can discuss and prioritize in another thread.  Thanks!

**Comment by shravnk** [comment]
OK thanks, will submit the PR and enter an omnibus RestGrid ticket
