### ISSUE TITLE
Refactor Rest components to leverage upgraded form support with validation

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#879]
The current RestGrid and associated RestForm have a pretty hard-coded implementation for rendering type-specific HoistInput controls. 

While providing a minimal-config setup experience (good) it has some drawbacks, notably that input configs can't be adjusted and there is no support for client-side validation.

This is a pretty significant ticket to revamp the rest editor components to use and benefit from the latest upgrades to Forms within Hoist.  (See #857 for the most recent master ticket there.)

**Comment by lbwexler** [comment]
Just merged this.  We may have additional API iterations surrounding built-in FieldModel types, and implementation changes when inputs autosizing is merged.
