### ISSUE TITLE
Add Mask Support to RestGrid

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#884]
+ Should be a one-liner to mask your RestGrid/RestGridModel.

+ When we fix this, we will want to apply to the Admin Grids as well as toolbox of course.
(unless we choose to make masking on by default, which is also a possibility)

**Comment by shravnk** [comment]
Went with a mask by default, disabled by prop `hideMask` on RestGrid. Let me know if we want to allow custom mask or not mask by default - will update admin grids accordingly.
