### ISSUE TITLE
Select - render selected option with a checkmark (mobile)

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#888]
This was recently implemented for the desktop library: https://github.com/exhi/hoist-react/issues/836

We should consider if we want to take a similar approach with the mobile select input.

**Comment by amcclain** [comment]
Agreed - @shravnk is going to take a look at this today.

**Comment by shravnk** [comment]
See https://github.com/exhi/hoist-react/tree/mobileSelectCheckmark
