### ISSUE TITLE
Consistent package location of column definition partials

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#901]
Our cross-platform column definition partials are nested under `@xh/hoist/cmp/grid/columns`
* These defs are not exported via the index file at `cmp/grid`, so an additional import is required to get the sub-package. They should be exported from the grid index file to keep with our pattern of not requiring `cmp` imports more than one level down.
* The desktop package maintains its desktop-specific partials under the `@xh/hoist/desktop/columns` package.  This should be moved to `@xh/hoist/desktop/cmp/grid/columns` and exported from the desktop grid index for consistency.

**Comment by shravnk** [comment]
See https://github.com/exhi/hoist-react/tree/columnPackageLocation

**Comment by shravnk** [comment]
and corresponding toolbox branch: https://github.com/exhi/toolbox/pull/140
