### ISSUE TITLE
Mobile Select displays banner at bottom of page

### ISSUE THREAD

**Issue by shravnk** [exhi/hoist-react#910]
When the react-select menu is focused and the menu is searchable, a keyboard is rendered at the bottom of the screen. There is a small banner containing the text 'Done' directly above the keyboard:

![image](https://user-images.githubusercontent.com/33368494/50777948-dc197500-126a-11e9-86c4-4422953a2579.png)

Our mobile Select component sets `isSearchable: false`, so we should never see this keyboard or banner. However, the banner is visible at the bottom of the screen:

![image](https://user-images.githubusercontent.com/33368494/50778058-11be5e00-126b-11e9-99f5-36dfa8e0d2c4.png)

To reproduce, visit toolbox-dev.xh.io/mobile on your phone. Select menus on the Forms and TreeGrid pages have this bug.

Did not see any react-select git issues describing this bug. It's a tough one to debug because can only be reproduced on mobile devices.

**Comment by lbwexler** [comment]
Hi @TomTirapani -- Can you take a look at this one and report back?  Do we need to do something here?  How critical is this?

**Comment by TomTirapani** [comment]
Taking a look now - will report back

**Comment by TomTirapani** [comment]
I'm not sure this is an issue. The "banner" that appears on focus exists to show the up / down tab arrows. When the input is not searchable, the keyboard should hide (and does), but _the banner should still be shown_ to allow navigation out of the field.

I think this is desired / correct behaviour, and think this issue can be closed.

However, during investigating this, I encountered two other issues with react-select on mobile:
https://github.com/exhi/hoist-react/issues/1190
https://github.com/exhi/hoist-react/issues/1191
