### ISSUE TITLE
Right click on a Grids' Context Menu opens Browser's Context menu

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#917]
1. Navigate to Hoist React Toolbox -> 'Grids > Standard' panel
2. Select and Right Click on a row
3. Grids Specific Context Menu list is displayed
4. Right Click on a control from the dropdown list
5. Browser's default context menu is displayed

**Comment by lbwexler** [comment]
Can you take a look at this one Brendan.  Definitely a bit annoying....

**Comment by shravnk** [comment]
See #1081

**Comment by lbwexler** [comment]
@haynesjm42, @amcclain for your review.  As I mentioned in the PR, happy to close this one.

**Comment by haynesjm42** [comment]
I am of the opinion that this is an ag-grid bug, if anything. Would vote for closing.

**Comment by lbwexler** [comment]
ag-Grid Bug.  If we had a clean way to fix it for them, we would, but this does not seem worth it.
