### ISSUE TITLE
Mobile Select Menu Should Block Scroll

### ISSUE THREAD

**Issue by shravnk** [exhi/hoist-react#923]
When the mobile select menu is open, it's still possible to scroll the underlying page. This means that the select menu is no longer vertically aligned with its button.

I tested a mask implementation [here](https://github.com/exhi/hoist-react/tree/mobileSelectMask). Tried two implementations:

1. Follow the mobile `Menu`'s pattern: return the `mask` and containing `box` as children of a `fragment` in `Select` (commented out in the branch). This would need more work as I had problems with positioning and DOM placement.
2. Create a bindable on XH.acm which controls a dedicated select mask in mobile AppContainer (currently configured in the branch).

A few items if we decide to go down this route:

1. Both methods (1) and (2) make use of react-select's onMenuOpen/Close event handlers. Would need to add some code to keep those accessible from `rsOptions`
2. `Select` nested within a `Menu` - When the select menu opens, there are two masks open and they layer on top of each other (i.e. underlying page appears a shade darker). Would want to avoid a mask in this case. Conversely, the select menu mask could simply be transparent (thinking this might actually be the best solution)
3. Would be interesting to see how this affects #910 . Unfortunately no way to test unless deployed

**Comment by shravnk** [comment]
Bumping this one as I think it's a good candidate for Hoist 20 inclusion. I think my suggestions above may be overkill - could simply default [menuShouldBlockScroll](https://react-select.com/props) to true for the mobile component. That fixes the problem, at least testing using Chrome mobile dev tools.

**Comment by lbwexler** [comment]
whoa -- I was just looking into this, and see the same API option than Brendan mentioned.  We should try this!  Looks like it easy bug to fix.

Yana, Tom can you two take a look at this?
