### ISSUE TITLE
Add client-side support for 'value dates'

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#925]
Its a very common problem for our business clients where the a field they want to display is a calendar date (e.g. settle date, trade date).  There is no time co-ordinate, and we don't want to express it as a javascript (or UTC) date that might be subject to timezone handling on different machines.

Support should be built around a YYYYMMDD representation of the date, and could include a dedicated HoistInput and built-in column type.

Probably useful for us to build this on top of our new DateInput control.

**Comment by lbwexler** [comment]
Again, good for some thoughtful work during your trip!

**Comment by lbwexler** [comment]
'CalendarDate' is ATM and my best take on it!  Feel free to suggest other names, but we like this one to start!

**Comment by TomTirapani** [comment]
PRs here:

https://github.com/exhi/hoist-react/pull/1130
https://github.com/exhi/toolbox/pull/191

Added a HoistInput, column type and form validator. Anything else we can think of to include?

**Comment by lbwexler** [comment]
Gents was thinking about this again -- was just looking at a client app that is really suffering due to the lack of support here -- they go back and forth all over the place between dates and strings,  in their management of a business day.  

Need to get support here for binding a dateinput to a YYMMDD date pronto.  Would like to re-up the priority here

**Comment by TomTirapani** [comment]
Happy to get back on this next week 👍
