### ISSUE TITLE
TextArea using word-wrap: break-word on Windows

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#927]
I do not see this on Mac, but observed on Windows on a client VM on Chrome v68.  Is see that the browser is applying `word-wrap:break-word` to `<textarea>` in its user agent stylesheet.  But this doesn't seem right / is not familiar to me...  What is going on?

<img width="488" alt="screen shot 2019-01-24 at 6 46 19 am" src="https://user-images.githubusercontent.com/225806/51685853-1477bd80-1fa4-11e9-9cbd-5d56e2d63cbe.png">

**Comment by cnrudd** [comment]
I don't see this issue on Windows 7 Chrome 73.0.3683.86 .  Words are not being broken.  Tested in toolbox and in the admin client config editor textbox.

**Comment by amcclain** [comment]
Testing again and not seeing it either.  Was definitely happening at one point - not sure if I caught a weird Chrome version or what - but very happy to close! Thanks for checking it out.
