### ISSUE TITLE
Upgrade to agGrid 20.x

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#942]

**Comment by amcclain** [comment]
Would be great to get this done in near future to stay current.  They also claim to have made some improvements to scrolling speed, which if true is always welcome.

Note a number of deprecations - will require adjustments to Hoist and any client apps doing more custom stuff with ag-grid. Might be reason to wait for v20 so we can get our current v19 changeset done and continue working on app updated to 18/19 without adding to the migration.

https://www.ag-grid.com/ag-grid-changelog/?fixVersion=20.0.0

(Funny that they refactored several of their configs to match what we've already put in place.)

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/947

**Comment by lbwexler** [comment]
👍
