### ISSUE TITLE
Allow Grid to show cell selection

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#946]
Our current Grid css hides cell selection with:

 .ag-cell-focus {
    border-color: var(--xh-grid-cell-focus-border-color) !important;
    outline: 0 !important;
  }

It is sometimes nice to see cell selection.  We should use a boolean prop to the Grid component that when true will add a css class to the grid to use alternate css that shows cell selection:

 .ag-cell-focus {
    border-color: var(--xh-green) !important;
    outline: 1px !important;
  }

While on the subject of cell navigation....
When cell navigation is visible, a tree group should open only when the left most cell is selected and the user hits the right arrow.  Right now, the group opens when any cell in the group row is selected and the user hits the right arrow.

Same for closing a tree group:  When cell navigation is visible, a left arrow event should only close the tree group when the left most cell is selected.

**Comment by amcclain** [comment]
Hi - submitted a PR to enable optional cell focus borders, along with the other new grid style flags we have teed up.

I was not seeing the different issue re. keyboard handling in the Toolbox treeGrid example.  The left/right arrows there only serve to navigate the selection.  Enter can be used to expand/collapse a group.  (And finally spacebar selects/deselects).  Can you check that out and let me know if I am missing something, or if this is an issue elsewhere?  If there's something outstanding there we can file a dedicated ticket.
