### ISSUE TITLE
HoistReact Timer should take a config key string with its interval

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#954]
Its a nice little convenience.  Best part of it is that timer reads the pref continually, adapting its interval and even shutting itself down as needed.

We have the same logic in HoistCore timer, just need to port it over from groovy to javascript!

**Comment by amcclain** [comment]
Config key, as opposed to pref?  We're not currently reloading configs in the app, although prefs can obviously change, which is part of why I wanted to confirm your thinking here.

Agree though would be a nice pickup / symmetry if we take a config key string directly - simpler to configure, and would set us up for changing configs on the client and having timers respect that. 👍

**Comment by lbwexler** [comment]
of course, thanks

**Comment by lbwexler** [comment]
Closing this -- we actually moved away from the tight coupling of config keys to timers on the server.

We have a related PR out that would make it easier to modify a timer's interval on the fly on the client, but don't think it is required to close this ticket.
