### ISSUE TITLE
Style DimChooser more like other controls

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#960]
Brendan found the following workaround.  Should it be in the toolkit?

.xh-dim-popover {
  .xh-button {
    background-color: var(--xh-bg);
  }
}

.xh-dark {
  .xh-dim-popover {
    .xh-button {
      background-color: var(--xh-input-bg);
    }
  }
}

**Comment by lbwexler** [comment]
brendan -- please have tom or atm review this change, thanks.

**Comment by shravnk** [comment]
Thanks for copying that, Lee. See Hoist tweak [here](https://github.com/exhi/hoist-react/tree/dimChooserBG). @amcclain would you mind double checking?

**Comment by amcclain** [comment]
Thanks for pushing on this!!  Have been meaning to ask or look for ages.  See commit for slightly different targeting but hopefully the same intended effect across light and dark themes.

**Comment by amcclain** [comment]
Sorry was rushing a bit and didn't mean to skip over 49edceb0b3f662f1194670528e02cb9ceedbc45e.  I don't recall exactly how the `&,` selector works - thinking that the change I pushed is a bit more explicit if not quite as cool 😄.  Please do let me know if I missed anything
