### ISSUE TITLE
Consider removing certain hyper-specific buttons from public API

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#973]
All of the overhead of maintaining an API for a very specific set of button defaults seems to me a little screwy and brittle.

(Looking at you RestoreDefaultsButton and LaunchAdminButton 😉 )

**Comment by amcclain** [comment]
As trivial as it is, we did see a use-case for the launch admin button in an app where we were not using the standard AppBar (another customer header was installed) but still wanted to have some standardized controls in an app toolbar.   I think they button up just enough "micro consistency" to be worthwhile in cases such as this one where we land "default" buttons in non-default places.

**Comment by lbwexler** [comment]
Happy to close this.  We can certainly revisit if they become too much of a maintenance burden)
