### ISSUE TITLE
Add AutoRefreshService to  Hoist

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#977]
Could be linked to a set of xh configs/preferences, and manages the timer to drive the app auto-refresh.  Really analogous to idleService.  Might need a flag on the AppSpec as well.

Note that a more sophisticated mechanism might make use of the fact that the RootRefreshContextModel knows when it was last refreshed manually as well.   Can potentially use a fast timer that examines that date before trying the auto-refresh.  Might avoid extra auto-refreshes when user is actively refreshing manually.

**Comment by shravnk** [comment]
See #1108, https://github.com/exhi/toolbox/tree/autoRefreshService, and https://github.com/exhi/hoist-core/tree/autoRefreshService
