### ISSUE TITLE
Add "clone" feature to REST grid, which would duplicate the selected record

### ISSUE THREAD

**Issue by nadkarniarjun** [exhi/hoist-react#984]
A request that was discussed with Anselm, Arjun, and John. We agreed to add it as a feature to Hoist.

**Comment by amcclain** [comment]
Thanks Arjun. As discussed:
* We would support this as an additional action - not enabled by default, so opt-in.
* Action would take the current single selected record and open a new add record form with the values from the source record pre-populated. User can then modify or cancel without saving - no requests or cloning is done on the server, it's a purely client-side convenience.
* It would be desirable to have a hook to allow a developer to specify a transform function to modify the source record in any appropriate way - e.g. by appending "Clone" or "Copy" to a primary name or identifier field. I believe this would have to be a function as we can't count on any given field or logic being appropriate. Could be something like a `prepareCloneFn` on `RestGridModel` ?

**Comment by haynesjm42** [comment]
An alternative approach to the transform hook would be to look for a callback in the action def itself, this is a pattern I've toyed with in client-apps where I use an action in multiple places which needs to have some kind of context injected into it, and I think this pattern worked out well for the Action column where we did something similar for the actions list.

App code could look something like this:
```
const myCloneAction = {
    ...restCloneAction,
    prepareCloneFn: ({sourceRecord, clone}) => {
        clone.name = `${sourceRecord.name}_CLONE`;
    }
};
```
