### ISSUE TITLE
Why doesn't hoist Label component use the html label element?

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#986]
The Hoist-React Label component:
https://github.com/exhi/hoist-react/blob/develop/desktop/cmp/input/Label.js

says it is "A simple label for a form."

but it is made with a DIV element, not a LABEL element.

This makes it not possible to use the native HTML 'for' attribute as a prop for 'htmlFor' on the Hoist-React Label component.

**Comment by lbwexler** [comment]
I think its unclear what the purpose of this component is.  Its a bit of a legacy.

**Comment by amcclain** [comment]
Yes, agreed.  Note that the `FormField` component *might*  be a better choice for wrapping inputs if you need a more full-featured Hoist component. It includes label support, but it uses the elemFactory for `<label>` out of https://github.com/exhi/hoist-react/blob/develop/cmp/layout/Tags.js#L28

Can we just delete this component? Do you see any value in it? I don't know why it has the BP classes, and I would be happy to drop it with a release note mention in the next major release.  Thanks for raising.

**Comment by cnrudd** [comment]
I see the Label component is used in 2 hoist react files:
hoist-react/admin/tabs/logging/viewer/LogViewerToolbar.js 
hoist-react/admin/tabs/monitor/MonitorResultsToolbar.js 

Do you still want to delete it?

**Comment by cnrudd** [comment]
In these files:
hoist-react/admin/tabs/logging/viewer/LogViewerToolbar.js
hoist-react/admin/tabs/monitor/MonitorResultsToolbar.js

it was super easy to replace:
https://github.com/exhi/hoist-react/blob/develop/desktop/cmp/input/Label.js
with
https://github.com/exhi/hoist-react/blob/develop/cmp/layout/Tags.js#L28

The rendered text had the exact same CSS properties.  Just now wrapped in a <label> tag.

I think deleting is the way to go.  I will submit a PR.
