### ISSUE TITLE
Refactor Record to store its data within a dedicated data property on the class

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#998]
For discussion - but it seems potentially problematic that the current Record implementation installs all of its use-case-specific data fields as top-level props on the class.  Should these be nested within a data map?  Do we have / want options to still allow them to be referenced right off of the object, or are we more comfortable with accessing through data or a getter ala Ext.Record?

**Comment by lbwexler** [comment]
We *may* take another crack at this with our next set of changes to the data package and GridModel.  
For discussion.

**Comment by lbwexler** [comment]
Am looking at this now.

**Comment by lbwexler** [comment]
We visited this question as part of some recent refactoring of LocalStore and decided that this would be disruptive, and that there were some advantages to having the flat record, namely that the "records" passed to callbacks in our API would be the same as the 'records" in the ag API.  Closing.
